import { COMBAT_GRAPH, encounterPhases, getPalKnowledge, normalizeElement } from '../knowledge/combat-graph.js';
import { PASSIVES } from '../data/passives.js';
import { optimizePassiveBuild } from './passive-builds.js';
import { optimizeSkillRotation } from './skill-rotations.js';

export const OPTIMIZER_API_VERSION='3.6.0';
export const ACTIVITY_MODELS=Object.freeze({
  normal_team:'single-active-pal',
  tower:'single-active-pal',
  alpha_boss:'single-active-pal',
  raid:'multi-active-army',
  base:'base-assignment',
  farm_loot:'conditional-farm-team',
  manual:'manual-interaction'
});

export const TEAM_OBJECTIVES=Object.freeze({
  practical:{id:'practical',label:'Bestes praktisches Team',passiveGoal:'practical'},
  element:{id:'element',label:'Bestes Elementteam',passiveGoal:'damage'},
  safest:{id:'safest',label:'Sicherstes Team',passiveGoal:'survival'},
  speedrun:{id:'speedrun',label:'Speedrun-Team',passiveGoal:'damage'}
});

const N=value=>Number.isFinite(Number(value))?Number(value):0;
const list=value=>Array.isArray(value)?value:[];
const sourceOf=node=>node?.sourceRef||node;
const effectsOf=pal=>list(pal?.partner?.effects);
const elementsOf=pal=>list(pal?.elements).length?pal.elements:String(pal?.element||'').split('/').map(normalizeElement).filter(Boolean);
const graphPals=()=>COMBAT_GRAPH.pals.filter(pal=>pal.playable);
const DEFAULT_PROFILE=Object.freeze({level:75,stars:0,passives:[],activeSkills:[],activeSkillIds:[],ivs:{hp:0,attack:0,defense:0},souls:{hp:0,attack:0,defense:0,work:0}});

function profileFor(state,pal,instance){
  const source=instance||state?.palProfiles?.[pal.id]||state?.palProfiles?.[pal.catalogId]||state?.palProfiles?.[pal.internalId]||{};
  return {...DEFAULT_PROFILE,...source,ivs:{...DEFAULT_PROFILE.ivs,...(source.ivs||{})},souls:{...DEFAULT_PROFILE.souls,...(source.souls||{})}};
}
function ownedIds(owned=[]){return new Set(owned.flatMap(item=>[item.catalogId,item.key,item.internalId,item.canonicalId].filter(Boolean)));}
function sourcePals(owned=[],constraints={}){const ids=ownedIds(owned);return graphPals().filter(pal=>!constraints.ownedOnly||ids.has(pal.id)||ids.has(pal.catalogId)||ids.has(pal.internalId)||pal.sourceIds.some(id=>ids.has(id)));}
function encounterElement(encounter){const weighted=new Map();for(const phase of encounterPhases(encounter)){for(const element of phase.elements||[])weighted.set(element,(weighted.get(element)||0)+(N(phase.hpShare)||1));}return [...weighted.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]||null;}
function requiredCounters(encounter){const weighted=new Map();for(const phase of encounterPhases(encounter)){for(const element of phase.recommendedCounters||[])weighted.set(normalizeElement(element),(weighted.get(normalizeElement(element))||0)+(N(phase.hpShare)||1));}return weighted;}

function passiveCandidateIds(element,goal){
  const wanted=new Set(goal==='survival'?['hp','defense','hpRegen','attack','cooldown','elementDamage']:['attack','elementDamage','cooldown','hp','defense','hpRegen']);
  return PASSIVES.rows.map(passive=>{let score=0;for(const effect of passive.effects){if(!wanted.has(effect.stat)||effect.value==null)continue;if(effect.stat==='elementDamage'&&element&&normalizeElement(effect.element)!==normalizeElement(element))continue;const weight={attack:5,elementDamage:5,cooldown:4,hp:2,defense:2,hpRegen:1.5}[effect.stat]||1;score+=Math.abs(N(effect.value))*weight;}return{id:passive.id,score};}).filter(row=>row.score>0).sort((a,b)=>b.score-a.score).slice(0,14).map(row=>row.id);
}
function passiveGoal(optimizationGoal){if(optimizationGoal==='safest'||optimizationGoal==='survival')return'survival';if(optimizationGoal==='speedrun'||optimizationGoal==='damage'||optimizationGoal==='element')return'damage';return'practical';}

function optimizeCarryBuild(pal,profile,encounter,optimizationGoal){
  const availableSkillIds=profile.activeSkillIds?.length?profile.activeSkillIds:profile.activeSkills?.length?profile.activeSkills:pal.skills.map(skill=>skill.id);
  const skillResult=optimizeSkillRotation({pal,encounter,availableSkillIds,duration:N(encounter?.timeLimit)||60,limit:3});
  if(skillResult.status!=='ok')return null;
  const element=elementsOf(pal)[0]||encounterElement(encounter),goal=passiveGoal(optimizationGoal);
  const passiveResult=optimizePassiveBuild({element,goal,mode:'combat',allowedPassiveIds:passiveCandidateIds(element,goal),limit:3});
  const bestPassive=passiveResult.status==='ok'?passiveResult.builds[0]:null,rotation=skillResult.winner;
  const attack=N(pal.stats?.attack),levelFactor=.55+Math.min(75,Math.max(1,N(profile.level||75)))/75*.45,ivFactor=1+Math.min(100,Math.max(0,N(profile.ivs?.attack)))*.003,soulFactor=1+Math.min(10,Math.max(0,N(profile.souls?.attack)))*.03,passiveFactor=bestPassive?.metrics?.powerGain||1;
  const modelDps=rotation.simulation.modelDps*attack*levelFactor*ivFactor*soulFactor*passiveFactor/100,qualityPenalty=rotation.simulation.dataQuality==='verified'&&bestPassive?.dataQuality==='verified'?1:.82;
  return {pal:sourceOf(pal),palKnowledge:pal,profile,rotation:rotation.skills,rotationModel:rotation.simulation,passiveBuild:bestPassive,passiveAlternatives:passiveResult.status==='ok'?passiveResult.builds.slice(1):[],relativeCombatValue:modelDps,estimatedDpsRange:{low:modelDps*.65*qualityPenalty,high:modelDps*1.05},assumptions:[...new Set([...rotation.simulation.assumptions,...(bestPassive?.explanation?.assumptions||[]),'Modellwert kombiniert Skillrotation, Basisangriff, Level, IV, Seelen und strukturierte Passives.'])],dataQuality:rotation.simulation.dataQuality==='verified'&&bestPassive?.dataQuality==='verified'?'verified':'modelled'};
}

function effectQuality(effect){if(effect?.status==='verified'&&effect?.confidence==='high')return 1;if(effect?.status==='community-tested')return .75;if(effect?.status==='modelled')return .5;if(effect?.status==='provisional')return .2;return 0;}
function valueAtRank(effect,rank=0){if(!Array.isArray(effect?.valuesByRank))return null;const value=effect.valuesByRank[Math.max(0,Math.min(4,N(rank)))];return value==null?null:Number(value);}
function effectGroup(effect){return effect?.stackingGroup||`${effect?.type||'unknown'}:${effect?.element||effect?.target||'general'}`;}
function supportWeights(objective){
  if(objective==='safest')return{pal_element_attack:5,weakpoint_damage:4,pal_attack:4,party_pal_attack:4,cooldown_reduction:4,party_follow_attack:3,player_attack:2,player_weapon_damage:2,damage_reduction:12,heal_player:10,revive_player:12,life_steal:9};
  if(objective==='speedrun')return{pal_element_attack:12,weakpoint_damage:12,pal_attack:10,party_pal_attack:10,cooldown_reduction:10,party_follow_attack:8,player_attack:7,player_weapon_damage:7,damage_reduction:1,heal_player:0,revive_player:0,life_steal:1};
  if(objective==='element')return{pal_element_attack:14,weakpoint_damage:12,pal_attack:6,party_pal_attack:6,cooldown_reduction:6,party_follow_attack:5,player_attack:3,player_weapon_damage:3,damage_reduction:2,heal_player:1,revive_player:1,life_steal:1};
  return{pal_element_attack:10,weakpoint_damage:9,pal_attack:8,party_pal_attack:8,cooldown_reduction:7,party_follow_attack:6,player_attack:5,player_weapon_damage:5,damage_reduction:5,heal_player:4,revive_player:4,life_steal:4};
}
function supportContribution(effect,pal,carry,rank=0,objective='practical'){
  if(effect?.activation!=='in_party')return null;const carryElements=elementsOf(carry.palKnowledge),targetElement=effect.element||effect.targetElement;if(targetElement&&!carryElements.includes(normalizeElement(targetElement)))return null;
  const weight=supportWeights(objective)[effect.type]||0,quality=effectQuality(effect);if(!weight||!quality)return null;const numeric=valueAtRank(effect,rank),utility=weight*quality*(numeric==null?.35:Math.min(3,Math.abs(numeric)/10));return{pal,effect,group:effectGroup(effect),stackable:effect.stackable===true,utility,numeric,reason:`${pal.partner?.name||'Partnerfähigkeit'} · ${effect.type}${numeric==null?' · Rangwert fehlt':` · ${numeric}`}`};
}
function supportCandidate(pal,carry,rank=0,objective='practical'){const contributions=effectsOf(pal).map(effect=>supportContribution(effect,pal,carry,rank,objective)).filter(Boolean);return{pal,contributions,utility:contributions.reduce((sum,item)=>sum+item.utility,0),reasons:contributions.map(item=>item.reason)};}

export function resolveStacking(contributions=[]){const groups=new Map();for(const item of contributions){if(!groups.has(item.group))groups.set(item.group,[]);groups.get(item.group).push(item);}const applied=[];for(const rows of groups.values()){const stackable=rows.filter(row=>row.stackable);if(stackable.length)applied.push(...stackable);const nonStackable=rows.filter(row=>!row.stackable).sort((a,b)=>b.utility-a.utility)[0];if(nonStackable)applied.push(nonStackable);}return{applied,suppressed:contributions.filter(item=>!applied.includes(item)),totalUtility:applied.reduce((sum,item)=>sum+item.utility,0)};}
function combinations(items,choose,start=0,prefix=[],out=[]){if(prefix.length===choose){out.push(prefix);return out;}for(let index=start;index<=items.length-(choose-prefix.length);index++)combinations(items,choose,index+1,[...prefix,items[index]],out);return out;}
function memberRole(member,carry){if(member.palKnowledge?.dexKey===carry.palKnowledge.dexKey)return'Aktiver Haupt-Pal';const types=effectsOf(member.palKnowledge).filter(effect=>effect.activation==='in_party').map(effect=>effect.type);if(types.some(type=>['pal_element_attack','weakpoint_damage','pal_attack','party_pal_attack'].includes(type)))return'Schadensverstärker';if(types.some(type=>['cooldown_reduction','party_follow_attack'].includes(type)))return'Tempo-Support';if(types.some(type=>['player_attack','player_weapon_damage'].includes(type)))return'Spieler-Support';if(types.some(type=>['heal_player','revive_player','life_steal','damage_reduction'].includes(type)))return'Sustain-Support';return'Wechsel-Pal';}
function phaseCoverage(carry,encounter){const phases=encounterPhases(encounter),skillElements=new Set(carry.rotation.map(skill=>normalizeElement(skill.element)));return phases.map(phase=>({phaseId:phase.id,hpShare:phase.hpShare,elements:phase.elements,covered:phase.recommendedCounters?.some(element=>skillElements.has(normalizeElement(element)))||phase.elements.length===0,recommendedCounters:phase.recommendedCounters}));}
function elementAlignment(carry,encounter){const counters=requiredCounters(encounter),skills=new Set(carry.rotation.map(skill=>normalizeElement(skill.element))),palElements=new Set(elementsOf(carry.palKnowledge).map(normalizeElement));let covered=0,total=0;for(const [element,weight] of counters){total+=weight;if(skills.has(element))covered+=weight;if(palElements.has(element))covered+=weight*.25;}return total?Math.min(1.25,covered/total):1;}
function survivalUtility(resolved){return resolved.applied.filter(item=>['damage_reduction','heal_player','revive_player','life_steal'].includes(item.effect.type)).reduce((sum,item)=>sum+item.utility,0);}
function offensiveUtility(resolved){return resolved.applied.filter(item=>['pal_element_attack','weakpoint_damage','pal_attack','party_pal_attack','cooldown_reduction','party_follow_attack','player_attack','player_weapon_damage'].includes(item.effect.type)).reduce((sum,item)=>sum+item.utility,0);}
function teamScore(carry,resolved,objective,coverage,encounter){const survival=survivalUtility(resolved),offense=offensiveUtility(resolved),uncovered=coverage.filter(phase=>!phase.covered).reduce((sum,phase)=>sum+N(phase.hpShare),0),alignment=elementAlignment(carry,encounter);if(objective==='element')return(carry.relativeCombatValue*.9+offense*1.15+survival*.1)*alignment*(1-uncovered*.45);if(objective==='safest')return(carry.relativeCombatValue*.55+offense*.35+survival*2.2)*(1-uncovered*.2);if(objective==='speedrun')return(carry.relativeCombatValue*1.45+offense*1.35+survival*.05)*(1-uncovered*.3);return(carry.relativeCombatValue+offense+survival*.55)*(1-uncovered*.3);}

function teamFromCandidate(candidate,playerState,objective){
  const supports=candidate.group.map(member=>({pal:sourceOf(member.pal),palKnowledge:member.pal,profile:profileFor(playerState,member.pal),rotation:[],passiveBuild:null,relativeCombatValue:0,estimatedDpsRange:null,supportUtility:candidate.resolved.applied.filter(item=>item.pal.dexKey===member.pal.dexKey).reduce((sum,item)=>sum+item.utility,0),supportReasons:member.reasons,appliedEffects:candidate.resolved.applied.filter(item=>item.pal.dexKey===member.pal.dexKey).map(item=>item.effect),suppressedEffects:candidate.resolved.suppressed.filter(item=>item.pal.dexKey===member.pal.dexKey).map(item=>item.effect)}));
  const members=[candidate.carry,...supports].map(member=>({...member,role:memberRole(member,candidate.carry)}));
  return{id:objective.id,label:objective.label,objective:objective.id,objectiveScore:candidate.score,members,relativeTeamValue:candidate.score,estimatedActivePalDpsRange:candidate.carry.estimatedDpsRange,phaseCoverage:candidate.phaseCoverage,elementAlignment:candidate.elementAlignment,dataQuality:candidate.carry.dataQuality,stacking:{applied:candidate.resolved.applied.map(item=>({palId:item.pal.id,dexKey:item.pal.dexKey,group:item.group,type:item.effect.type,value:item.numeric})),suppressed:candidate.resolved.suppressed.map(item=>({palId:item.pal.id,dexKey:item.pal.dexKey,group:item.group,type:item.effect.type}))},assumptions:[...candidate.carry.assumptions,`Eigene Zielfunktion: ${objective.label}.`,'Genau ein aktiver Pal verursacht eigenen Pal-Schaden.','Support-Pals werden nur über strukturierte activation=in_party-Effekte bewertet.','Nicht stapelbare Effekte derselben stackingGroup werden nur einmal gewertet.','Bossphasen werden über hpShare gewichtet.','Keine sekundengenaue reale DPS-Garantie.']};
}

function bestCandidateForObjective({source,encounter,playerState,objective}){
  const carries=source.map(pal=>optimizeCarryBuild(pal,profileFor(playerState,pal),encounter,objective.id)).filter(Boolean).sort((a,b)=>b.relativeCombatValue-a.relativeCombatValue).slice(0,12);let best=null;
  for(const carry of carries){const pool=source.filter(pal=>pal.dexKey!==carry.palKnowledge.dexKey).map(pal=>supportCandidate(pal,carry,N(profileFor(playerState,pal).stars),objective.id)).filter(item=>item.utility>0).sort((a,b)=>b.utility-a.utility).slice(0,18);if(pool.length<4)continue;const coverage=phaseCoverage(carry,encounter);for(const group of combinations(pool,4)){const resolved=resolveStacking(group.flatMap(member=>member.contributions)),score=teamScore(carry,resolved,objective.id,coverage,encounter),candidate={carry,group,resolved,phaseCoverage:coverage,elementAlignment:elementAlignment(carry,encounter),score};if(!best||score>best.score)best=candidate;}}
  return best;
}

function optimizeSingleActive({encounter,playerState,ownedPals,constraints,optimizationGoal,activity}){
  const source=sourcePals(ownedPals,constraints);if(!source.length)return{status:'insufficient-data',model:ACTIVITY_MODELS[activity],reason:'Keine geeigneten Pals in der gewählten Datenbasis.',teams:[],dataQuality:'missing'};
  const objectives=[TEAM_OBJECTIVES.element,TEAM_OBJECTIVES.practical,TEAM_OBJECTIVES.safest,TEAM_OBJECTIVES.speedrun],teams=[];
  for(const objective of objectives){const candidate=bestCandidateForObjective({source,encounter,playerState,objective});if(candidate)teams.push(teamFromCandidate(candidate,playerState,objective));}
  if(!teams.length)return{status:'insufficient-data',model:ACTIVITY_MODELS[activity],reason:'Keine vollständige Fünferkombination mit drei auswertbaren Carry-Skills und vier nachvollziehbaren In-Party-Supports verfügbar.',teams:[],dataQuality:'missing'};
  return{status:'ok',model:ACTIVITY_MODELS[activity],optimizationGoal,teams,dataQuality:teams.every(team=>team.dataQuality==='verified')?'verified':'modelled'};
}

function raidInstances(owned=[]){return owned.map((instance,index)=>{const pal=getPalKnowledge(instance.catalogId||instance.canonicalId||instance.key||instance.internalId);return pal?.playable?{instance:{...instance,uniqueId:instance.uniqueId||`legacy-${index}`},pal}:null;}).filter(Boolean);}
function optimizeRaid({encounter,playerState,ownedPals,constraints,optimizationGoal}){const limit=N(constraints?.baseLimit||playerState?.raidBaseLimit);if(!limit)return{status:'insufficient-data',model:'multi-active-army',reason:'Für das Raid-Modell muss das tatsächliche Basislimit erfasst sein.',armies:[],dataQuality:'missing'};const rows=raidInstances(ownedPals).map(({instance,pal})=>{const model=optimizeCarryBuild(pal,profileFor(playerState,pal,instance),encounter,optimizationGoal);return model?{...model,instance,raidEffects:effectsOf(pal).filter(effect=>effect.activation==='raid_deployed')}:null;}).filter(Boolean).sort((a,b)=>b.relativeCombatValue-a.relativeCombatValue);if(!rows.length)return{status:'insufficient-data',model:'multi-active-army',reason:'Keine konkreten eigenen Raid-Pals mit auswertbarer Rotation vorhanden.',armies:[],dataQuality:'missing'};const deployed=rows.slice(0,limit),reserve=rows.slice(limit),waves=[];for(let index=0;index<rows.length;index+=Math.max(1,limit))waves.push(rows.slice(index,index+Math.max(1,limit)));return{status:'ok',model:'multi-active-army',optimizationGoal,armies:[{id:'owned-raid-army',label:'Beste Armee aus konkreten eigenen Exemplaren',deployed,reserve,waves,baseLimit:limit,estimatedArmyDpsRange:{low:deployed.reduce((sum,item)=>sum+item.estimatedDpsRange.low,0),high:deployed.reduce((sum,item)=>sum+item.estimatedDpsRange.high,0)},dataQuality:'modelled',assumptions:['Mehrere eingesetzte Exemplare verursachen eigenen Pal-Schaden.','Jedes Exemplar wird nur einmal verwendet.','Ausfälle, Wechselzeiten und Bossphasen werden noch nicht vollständig als Raid-Zeitachse simuliert.']}],dataQuality:'modelled'};}
function optimizeBase({encounter,ownedPals,constraints}){const workType=encounter?.workType;if(!workType)return{status:'insufficient-data',model:'base-assignment',reason:'Eine konkrete Arbeitsart ist erforderlich.',assignments:[],dataQuality:'missing'};const rows=raidInstances(ownedPals).map(({instance,pal})=>({instance,pal:sourceOf(pal),palKnowledge:pal,workLevel:N(pal.work?.[workType]),stars:N(instance.stars),baseEffects:effectsOf(pal).filter(effect=>effect.activation==='base_assigned')})).filter(item=>item.workLevel>0).sort((a,b)=>b.workLevel-a.workLevel||b.stars-a.stars);if(!rows.length)return{status:'insufficient-data',model:'base-assignment',reason:'Kein eigenes Exemplar besitzt die ausgewählte Arbeitseignung.',assignments:[],dataQuality:'missing'};const slots=N(constraints?.slots)||rows.length;return{status:'ok',model:'base-assignment',assignments:rows.slice(0,slots),alternatives:rows.slice(slots),metric:'Arbeitseignungslevel; keine Produktionsrate',dataQuality:'verified',assumptions:['Keine Material-pro-Stunde-Angabe ohne verifizierte Produktions- und Laufwegdaten.']};}
function farmMatches(effect,encounter){const target=encounter?.targetElement||encounter?.target||encounter?.materialId;return!target||effect.target===target||effect.element===target||effect.materialId===target;}
function optimizeFarm({encounter,ownedPals,constraints}){const allowed=new Set(['in_party','summoned','pal_defeats_target','manual_pickup','ranch']);const rows=raidInstances(ownedPals).flatMap(({instance,pal})=>effectsOf(pal).filter(effect=>allowed.has(effect.activation)&&farmMatches(effect,encounter)&&['pal_drop_bonus','item_weight_reduction','capture_bonus','manual_duplicate','loot_bonus','farm_drop'].includes(effect.type)).map(effect=>({instance,pal:sourceOf(pal),palKnowledge:pal,effect,activation:effect.activation,requiresEquipment:Boolean(effect.requiresEquipment),equipmentId:effect.equipmentId||null,quality:effectQuality(effect),value:valueAtRank(effect,N(instance.stars))})));if(!rows.length)return{status:'insufficient-data',model:'conditional-farm-team',reason:'Kein passender strukturierter Farm- oder Loot-Effekt im eigenen Bestand.',teams:[],dataQuality:'missing'};const selected=rows.sort((a,b)=>b.quality-a.quality||(b.value??-Infinity)-(a.value??-Infinity)).slice(0,N(constraints?.teamSize)||5);return{status:'ok',model:'conditional-farm-team',teams:[{id:'farm-team',members:selected,metric:'Strukturierte Aktivierungs- und Loot-Effekte; keine unbelegte Rate'}],dataQuality:selected.every(row=>row.effect.status==='verified')?'verified':'provisional'};}
function optimizeManual({encounter,ownedPals}){const activation=encounter?.activation;if(!activation)return{status:'insufficient-data',model:'manual-interaction',reason:'Eine konkrete Aktivierungsart ist erforderlich.',options:[],dataQuality:'missing'};const options=raidInstances(ownedPals).flatMap(({instance,pal})=>effectsOf(pal).filter(effect=>effect.activation===activation).map(effect=>({instance,pal:sourceOf(pal),palKnowledge:pal,effect,ready:!effect.requiresEquipment||Boolean(instance.saddleOwned),missingRequirement:effect.requiresEquipment&&!instance.saddleOwned?(effect.equipmentId||'Sattel/Ausrüstung'):null})));if(!options.length)return{status:'insufficient-data',model:'manual-interaction',reason:'Keine passende strukturierte Fähigkeit im eigenen Bestand.',options:[],dataQuality:'missing'};return{status:'ok',model:'manual-interaction',options,dataQuality:options.every(option=>option.effect.status==='verified')?'verified':'provisional'};}

export function optimizeTeam({activity,encounter,playerState={},ownedPals=[],constraints={},optimizationGoal='practical'}={}){if(!activity)throw new Error('activity is required');if(!encounter)throw new Error('encounter is required');if(!ACTIVITY_MODELS[activity])throw new Error(`unsupported activity: ${activity}`);const input={activity,encounter,playerState,ownedPals,constraints,optimizationGoal};if(['normal_team','tower','alpha_boss'].includes(activity))return optimizeSingleActive(input);if(activity==='raid')return optimizeRaid(input);if(activity==='base')return optimizeBase(input);if(activity==='farm_loot')return optimizeFarm(input);return optimizeManual(input);}
