import { loadState } from '../storage.js';
import { RAID_PROFILES, TOWER_PROFILES } from '../encounter-overrides.js';
import { optimizeTeam, OPTIMIZER_API_VERSION, ACTIVITY_MODELS } from './engine.js';

const app=document.querySelector('#app');
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const QUALITY={verified:'Verifiziert',modelled:'Modelliert',provisional:'Vorläufig',missing:'Fehlend'};
const WORK={kindling:'Feuer machen',watering:'Bewässern',planting:'Aussäen',generating:'Strom erzeugen',handiwork:'Handwerk',gathering:'Sammeln',lumbering:'Holzfällen',mining:'Bergbau',oilExtraction:'Ölförderung',medicine:'Medizin',cooling:'Kühlen',transporting:'Transport',farming:'Farm'};
const ACTIVATIONS={manual_pickup:'Manuell einsammeln',summoned:'Pal aktiv beschworen',mounted:'Auf Pal reiten',pal_defeats_target:'Pal besiegt Ziel',player_attack:'Spieler greift an',in_party:'Nur im Team',base_assigned:'Basis zugewiesen',ranch:'Ranch'};
const LABELS={normal_team:'Normales Fünferteam',tower:'Tower-Boss',alpha_boss:'Alpha-Boss',raid:'Raid-Armee',base:'Basisarbeit',farm_loot:'Farm & Loot',manual:'Manuelle Spezialinteraktion'};

function quality(v){return QUALITY[v]||v||'Offen';}
function assumptions(items=[]){return items.length?`<details><summary>Annahmen und Grenzen</summary><ul>${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></details>`:'';}
function palName(row){return row?.pal?.name||row?.name||'Unbekannt';}
function standardTeam(team){return `<section class="optimizer-team-grid">${team.members.map(member=>`<article class="optimizer-member"><span class="badge">${esc(member.role)}</span><h4>${esc(member.pal.name)}</h4><p class="element-line">${esc(member.pal.element||'Element offen')}</p><p><strong>Einsatz:</strong> ${member.rotation?.length?esc(member.rotation.map(x=>x.name).join(' → ')):'Kein eigener Pal-DPS; nur anwendbare Partywirkung'}</p>${member.supportReasons?.length?`<p><strong>Nutzen:</strong> ${esc(member.supportReasons.join(' · '))}</p>`:''}</article>`).join('')}</section><section class="card"><h3>Relativer Teamwert ${team.relativeTeamValue.toFixed(1)}</h3><p>${team.estimatedActivePalDpsRange?`Modellbereich des aktiven Pals: ${Math.round(team.estimatedActivePalDpsRange.low)}–${Math.round(team.estimatedActivePalDpsRange.high)}.`:'Kein Schadensbereich.'}</p><p>Datenqualität: ${quality(team.dataQuality)}</p>${assumptions(team.assumptions)}</section>`;}
function raidView(army){return `<section class="card"><p class="eyebrow">RAID-ARMEE</p><h3>${esc(army.label)}</h3><p>${army.deployed.length} aktiv · ${army.reserve.length} Reserve · Basislimit ${army.baseLimit}</p><p>Modellbereich der gleichzeitig eingesetzten Pals: ${Math.round(army.estimatedArmyDpsRange.low)}–${Math.round(army.estimatedArmyDpsRange.high)}.</p>${assumptions(army.assumptions)}</section><section class="list">${army.deployed.map((x,i)=>`<div class="list-item"><div><strong>${i+1}. ${esc(x.pal.name)}</strong><small>${esc(x.instance.uniqueId)} · Lv. ${x.profile.level} · ${x.rotation.map(s=>s.name).join(' → ')}</small></div><span class="badge">aktiv</span></div>`).join('')}</section>`;}
function baseView(result){return `<section class="card"><h3>Empfohlene Basisbesetzung</h3><p>${esc(result.metric)}</p>${assumptions(result.assumptions)}</section><section class="list">${result.assignments.map(x=>`<div class="list-item"><div><strong>${esc(x.pal.name)}</strong><small>${esc(x.instance.uniqueId)} · ${x.stars}★</small></div><span class="badge">Arbeit ${x.workLevel}</span></div>`).join('')}</section>`;}
function farmView(team){return `<section class="card"><h3>${esc(team.label)}</h3><p>Keine Ertragsrate wird ohne belegte Werte ausgegeben.</p></section><section class="list">${team.members.map(x=>`<div class="list-item"><div><strong>${esc(x.pal.name)}</strong><small>Aktivierung: ${esc(ACTIVATIONS[x.activation]||x.activation)}${x.requiresEquipment?` · benötigt ${esc(x.equipmentId||'Ausrüstung')}`:''}</small></div><span class="badge">${x.value||'Wert offen'}</span></div>`).join('')}</section>`;}
function manualView(result){return `<section class="list">${result.options.map(x=>`<div class="list-item ${x.ready?'':'warning'}"><div><strong>${esc(x.pal.name)}</strong><small>${esc(ACTIVATIONS[x.activation]||x.activation)}${x.missingRequirement?` · fehlt: ${esc(x.missingRequirement)}`:''}</small></div><span class="badge ${x.ready?'':'pending'}">${x.ready?'bereit':'nicht bereit'}</span></div>`).join('')}</section>${assumptions(result.assumptions)}`;}
function resultView(result,encounter){if(result.status!=='ok')return`<section class="card warning"><p class="eyebrow">KEINE BELASTBARE EMPFEHLUNG</p><h3>${esc(result.reason)}</h3><p>Datenqualität: ${quality(result.dataQuality)}</p></section>`;if(result.model==='single-active-pal')return`<section class="card optimizer-sticky"><p class="eyebrow">${esc(encounter.name||LABELS.normal_team)}</p><h3>Ein aktiver Pal, vier passive Partyplätze</h3></section>${standardTeam(result.teams[0])}`;if(result.model==='multi-active-army')return raidView(result.armies[0]);if(result.model==='base-assignment')return baseView(result);if(result.model==='conditional-farm-team')return`${farmView(result.teams[0])}${assumptions(result.assumptions)}`;if(result.model==='manual-interaction')return manualView(result);return'';}
function encounterControls(activity){if(activity==='tower')return`<div class="field"><label>Schwierigkeit</label><select name="difficulty"><option>Normal</option><option>Schwer</option></select></div><div class="field wide"><label>Boss</label><select name="encounter"></select></div>`;if(activity==='raid')return`<div class="field wide"><label>Raid</label><select name="encounter">${RAID_PROFILES.map(x=>`<option value="${esc(x.id)}">${esc(x.name)} · Lv. ${x.level}</option>`).join('')}</select></div><div class="field"><label>Tatsächliches Basislimit</label><input name="baseLimit" type="number" min="1" required></div>`;if(activity==='normal_team'||activity==='alpha_boss')return`<div class="field"><label>Zielname</label><input name="name" required placeholder="z. B. Alpha Anubis"></div><div class="field"><label>Zielelement</label><select name="element">${['Neutral','Feuer','Wasser','Gras','Elektro','Eis','Erde','Schatten','Drache'].map(x=>`<option>${x}</option>`).join('')}</select></div>`;if(activity==='base')return`<div class="field wide"><label>Arbeitsart</label><select name="workType">${Object.entries(WORK).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></div><div class="field"><label>Plätze</label><input name="slots" type="number" min="1" value="1"></div>`;if(activity==='farm_loot')return`<div class="field"><label>Ziel / Element / Material-ID</label><input name="target" required placeholder="z. B. Elektro oder Chromit"></div><div class="field"><label>Teamgröße</label><input name="teamSize" type="number" min="1" max="5" value="5"></div>`;return`<div class="field"><label>Aktivierungsart</label><select name="activation">${Object.entries(ACTIVATIONS).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></div><div class="field"><label>Ziel</label><input name="target" placeholder="optional"></div>`;}
function buildEncounter(activity,values,difficulty){if(activity==='tower')return TOWER_PROFILES.filter(x=>x.difficulty===difficulty).find(x=>x.id===values.encounter);if(activity==='raid')return RAID_PROFILES.find(x=>x.id===values.encounter);if(activity==='normal_team'||activity==='alpha_boss')return{name:values.name,elements:[values.element]};if(activity==='base')return{name:WORK[values.workType],workType:values.workType};if(activity==='farm_loot')return{name:values.target,target:values.target,targetElement:values.target,materialId:values.target};return{name:values.target||ACTIVATIONS[values.activation],target:values.target,activation:values.activation};}
async function openOptimizer(activity){const state=await loadState({pals:[],palProfiles:{},playerLoadout:{}});let difficulty='Normal';const render=()=>{app.innerHTML=`<button class="back-link" data-central-back>‹ Optimieren</button><section class="hero compact-hero"><div><p class="eyebrow">ZENTRALE ENGINE ${OPTIMIZER_API_VERSION}</p><h2>${esc(LABELS[activity])}</h2><p>Berechnungsmodell: ${esc(ACTIVITY_MODELS[activity])}</p></div></section><form class="card form" id="centralOptimizerForm">${encounterControls(activity)}${['normal_team','tower','alpha_boss'].includes(activity)?`<div class="field"><label>Datenbasis</label><select name="scope"><option value="all">Alle fangbaren Pals</option><option value="owned">Nur mein Bestand</option></select></div>`:''}<button class="primary">Berechnen</button></form><div id="centralOptimizerResult"></div>`;const form=document.querySelector('#centralOptimizerForm');const fillTower=()=>{if(activity!=='tower')return;form.elements.encounter.innerHTML=TOWER_PROFILES.filter(x=>x.difficulty===difficulty).map(x=>`<option value="${esc(x.id)}">${esc(x.name)} · Lv. ${x.level}</option>`).join('');};fillTower();form.elements.difficulty?.addEventListener('change',e=>{difficulty=e.target.value;fillTower();});form.addEventListener('submit',e=>{e.preventDefault();const values=Object.fromEntries(new FormData(form)),encounter=buildEncounter(activity,values,difficulty),result=optimizeTeam({activity,encounter,playerState:state,ownedPals:state.pals||[],constraints:{ownedOnly:values.scope==='owned',baseLimit:Number(values.baseLimit),slots:Number(values.slots),teamSize:Number(values.teamSize)},optimizationGoal:'practical'});document.querySelector('#centralOptimizerResult').innerHTML=resultView(result,encounter);});document.querySelector('[data-central-back]')?.addEventListener('click',renderHub);};render();}
function renderHub(){const cards=[['normal_team','◉','Normales Team','Ein aktiver Pal und vier Party-Effekte'],['tower','⚔','Tower & Boss','Bossprofil und Fünferteam'],['alpha_boss','△','Alpha-Boss','Manuelles Alpha-Ziel'],['raid','◈','Raid-Armee','Eigene Exemplare, Basislimit und Wellen'],['base','⌂','Basisarbeit','Arbeitseignung statt Kampfscore'],['farm_loot','◇','Farm & Loot','Aktivierungsbedingungen und Zielbezug'],['manual','✋','Spezialinteraktion','Aktiv-, Sattel- und Pickup-Prüfung']];app.innerHTML=`<section class="hero"><div><p class="eyebrow">PHASE 2</p><h2>Getrennte Modelle statt Universalscore</h2><p>Jede Aktivität verwendet ihre eigene fachliche Logik.</p></div></section><div class="module-grid">${cards.map(([id,icon,title,text])=>`<button class="module-card" data-central-activity="${id}"><div class="module-icon">${icon}</div><div><h3>${title}</h3><p>${text}</p></div><span class="badge">Aktiv</span></button>`).join('')}</div>`;document.querySelectorAll('[data-central-activity]').forEach(b=>b.addEventListener('click',()=>openOptimizer(b.dataset.centralActivity)));}
export function installOptimizerUI(){document.addEventListener('click',event=>{const tab=event.target.closest('.tab[data-route="optimieren"]'),legacy=event.target.closest('[data-cluster="boss"],[data-cluster="raid"]');if(!tab&&!legacy)return;event.preventDefault();event.stopImmediatePropagation();legacy?openOptimizer(legacy.dataset.cluster==='raid'?'raid':'tower'):renderHub();},true);}
const style=document.createElement('style');style.textContent=`.optimizer-team-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px}.optimizer-member{background:linear-gradient(145deg,rgba(40,47,64,.82),rgba(20,24,34,.72));border:1px solid var(--line);border-radius:18px;padding:14px;min-width:0}.optimizer-member h4{margin:10px 0 6px}.optimizer-member p{font-size:12px;color:var(--muted);line-height:1.4}.optimizer-sticky{position:sticky;top:8px;z-index:3}@media(max-width:680px){.optimizer-team-grid{display:flex;overflow-x:auto;scroll-snap-type:x mandatory;padding-bottom:8px}.optimizer-member{min-width:78%;scroll-snap-align:start}}`;document.head.appendChild(style);
