import { loadState, saveState as persistState } from './storage.js';
import { PAL_CATALOG, CATALOG_VERSION } from './catalog.js';

const defaultState={schemaVersion:3,profile:{playerLevel:'',world:'',goal:'',goalType:'boss'},pals:[],equipment:[],materials:[],bases:[],teamPlans:[],updatedAt:null};
let state=await loadState(defaultState);state={...defaultState,...state,profile:{...defaultState.profile,...state.profile},pals:state.pals||[],teamPlans:state.teamPlans||[]};
let route='dashboard';let search='';const app=document.querySelector('#app');
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function save(){state.schemaVersion=3;state.updatedAt=new Date().toISOString();await persistState(state)}
function owned(catalogId){return state.pals.some(p=>p.catalogId===catalogId)}
function decision(){if(!state.profile.playerLevel)return['Spielerlevel ergänzen','Nur erreichbare Inhalte dürfen berücksichtigt werden.','bestand'];if(!state.profile.goal)return['Ziel festlegen','Ohne konkretes Ziel gibt es keine belastbare Optimierung.','bestand'];if(!state.pals.length)return['Pals aus dem Katalog übernehmen','Wähle deine tatsächlich vorhandenen Pals direkt aus dem verifizierten Paldex.','paldex'];return[`${state.profile.goal} vorbereiten`,`${state.pals.length} eigene Pals stehen für spätere Berechnungen bereit.`,'optimieren']}
function dashboard(){const[t,w,target]=decision();return`<section class="hero"><div><p class="eyebrow">NÄCHSTER BESTER SCHRITT</p><h2>${esc(t)}</h2><p>${esc(w)}</p></div><button class="primary" data-go="${target}">Jetzt bearbeiten</button></section><div class="grid"><article class="card"><span class="muted">Verifizierter Katalog</span><div class="metric">${PAL_CATALOG.length}</div><p>Pals mit deutschem Partnerfähigkeitstext</p></article><article class="card"><span class="muted">Mein Bestand</span><div class="metric">${state.pals.length}</div><p>lokal gespeicherte Pals</p></article></div><section class="card"><p class="eyebrow">DATENQUALITÄT</p><h3>Keine stillen Annahmen</h3><p>Der Katalog wächst paketweise. Nur geprüfte deutsche Spieltexte werden als bestätigt markiert.</p></section>`}
function bestand(){return`<section class="card"><p class="eyebrow">MEIN SPIELSTAND</p><h3>Berechnungsgrundlage</h3><form id="profileForm" class="form"><div class="field"><label>Spielerlevel</label><input name="playerLevel" type="number" min="1" value="${esc(state.profile.playerLevel)}"></div><div class="field"><label>Welt</label><input name="world" value="${esc(state.profile.world)}"></div><div class="field"><label>Ziel</label><input name="goal" value="${esc(state.profile.goal)}" placeholder="z. B. Lily Hard besiegen"></div><button class="primary">Speichern</button></form></section><section class="card"><div class="section-title"><h2>Meine Pals</h2><button data-go="paldex">Aus Katalog</button></div>${state.pals.length?`<div class="list">${state.pals.map((p,i)=>`<div class="list-item"><div><strong>${esc(p.name)}</strong><small>#${esc(p.catalogId||'frei')} · ${p.stars||0}★ · Level ${esc(p.level||'offen')}</small></div><button class="secondary compact" data-remove-pal="${i}">×</button></div>`).join('')}</div>`:`<div class="empty"><strong>Noch keine Pals</strong><p class="muted">Übernimm sie direkt aus dem Paldex.</p></div>`}</section>`}
function paldex(){const q=search.trim().toLowerCase();const rows=PAL_CATALOG.filter(p=>!q||`${p.id} ${p.name} ${p.partner.name} ${p.partner.description}`.toLowerCase().includes(q));return`<section class="hero compact-hero"><div><p class="eyebrow">PALDEX · DATENPAKET 1</p><h2>Geprüfte deutsche Partnerfähigkeiten</h2><p>${PAL_CATALOG.length} Einträge sind lokal eingebaut. Weitere Datenpakete folgen ohne Laufzeit-API.</p></div></section><section class="card"><div class="field"><label>Pal oder Fähigkeit suchen</label><input id="catalogSearch" value="${esc(search)}" placeholder="z. B. Penking, Beute, Schatten"></div></section><div class="catalog-list">${rows.map(p=>`<article class="catalog-card"><div class="catalog-head"><div><span class="badge">#${p.id}</span><h3>${esc(p.name)}</h3></div><span class="verified">Geprüft</span></div><strong>${esc(p.partner.name)}</strong><p>${esc(p.partner.description)}</p><button class="${owned(p.id)?'secondary':'primary'}" data-own="${p.id}" ${owned(p.id)?'disabled':''}>${owned(p.id)?'Im Bestand':'Zu meinem Bestand'}</button></article>`).join('')}</div>${rows.length?'':'<div class="empty">Keine Treffer</div>'}`}
function optimieren(){return`<section class="hero"><div><p class="eyebrow">ENTSCHEIDUNGSENGINE</p><h2>Grundlage wird belastbar</h2><p>Der Team Builder wird im nächsten Schritt direkt auf Katalog-IDs, Partnerfähigkeiten und später aktive sowie passive Fähigkeiten umgestellt.</p></div><button class="primary" data-go="paldex">Katalog prüfen</button></section><section class="card"><h3>Aktuell berechenbar</h3><p>${state.pals.length?`${state.pals.length} Pals sind eindeutig mit dem Katalog verknüpft.`:'Noch kein Pal wurde aus dem Katalog übernommen.'}</p></section>`}
function mehr(){return`<section class="card"><p class="eyebrow">DATENSTAND</p><h3>${esc(CATALOG_VERSION)}</h3><p>Deutscher Partnerfähigkeiten-Katalog, Paket 1. Alle Daten liegen offline in PALWERK.</p></section><section class="card"><h3>Backup</h3><div class="button-stack"><button class="secondary" data-export>Backup exportieren</button><label class="secondary file-button">Backup importieren<input type="file" accept="application/json" data-import></label></div></section>`}
function render(){app.innerHTML=({dashboard,bestand,paldex,optimieren,mehr})[route]();document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.route===route));bind()}
function bind(){document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>navigate(x.dataset.go));document.querySelector('#profileForm')?.addEventListener('submit',async e=>{e.preventDefault();state.profile={...state.profile,...Object.fromEntries(new FormData(e.currentTarget))};await save();render()});document.querySelector('#catalogSearch')?.addEventListener('input',e=>{search=e.target.value;render()});document.querySelectorAll('[data-own]').forEach(x=>x.onclick=()=>addOwned(x.dataset.own));document.querySelectorAll('[data-remove-pal]').forEach(x=>x.onclick=async()=>{state.pals.splice(+x.dataset.removePal,1);await save();render()});document.querySelector('[data-export]')?.addEventListener('click',exportBackup);document.querySelector('[data-import]')?.addEventListener('change',importBackup)}
async function addOwned(id){const c=PAL_CATALOG.find(p=>p.id===id);if(!c||owned(id))return;const level=prompt(`Level von ${c.name} (optional)`,'')||'';const stars=Math.max(0,Math.min(4,Number(prompt('Sterne 0–4','0')||0)));state.pals.push({id:crypto.randomUUID(),catalogId:c.id,name:c.name,partner:c.partner,level,stars,passives:[],skills:[],implants:[]});await save();render()}
function exportBackup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`palwerk-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
async function importBackup(e){try{const f=e.target.files?.[0];if(!f)return;const p=JSON.parse(await f.text());if(!p.profile||!Array.isArray(p.pals))throw new Error();state={...defaultState,...p,schemaVersion:3};await save();render()}catch{alert('Das Backup ist ungültig.')}}
function navigate(next){route=next;render();scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.tab').forEach(x=>x.onclick=()=>navigate(x.dataset.route));
function connection(){document.querySelector('#offlineStatus').textContent=navigator.onLine?'Lokal bereit':'Offline aktiv'}
addEventListener('online',connection);addEventListener('offline',connection);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');connection();render();
