import { loadState, saveState as persistState } from './storage.js';
import { PAL_CATALOG, CATALOG_VERSION, WORK_LABELS, DATA_STATUS_LABELS, validateCatalog } from './catalog.js';

const defaultState={schemaVersion:4,profile:{playerLevel:'',world:'',goal:'',goalType:'boss'},pals:[],equipment:[],materials:[],bases:[],teamPlans:[],updatedAt:null};
let state=await loadState(defaultState);state={...defaultState,...state,profile:{...defaultState.profile,...state.profile},pals:state.pals||[]};
let route='dashboard',search='',elementFilter='',workFilter='',statusFilter='',detailKey='';const app=document.querySelector('#app');
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const catalogByName=name=>PAL_CATALOG.find(p=>p.name.toLowerCase()===String(name||'').toLowerCase());
for(const p of state.pals){const c=PAL_CATALOG.find(x=>x.key===p.catalogId)||catalogByName(p.name);if(c){p.catalogId=c.key;p.name=c.name;p.paldeck=c.paldeck}}
async function save(){state.schemaVersion=4;state.updatedAt=new Date().toISOString();await persistState(state)}
await save();
function owned(key){return state.pals.some(p=>p.catalogId===key)}
function deckLabel(p){return p.paldeck?`#${p.paldeck}`:'Nr. wird geprüft'}
function workText(p){const entries=Object.entries(p.work||{}).sort((a,b)=>b[1]-a[1]);return entries.length?entries.map(([k,v])=>`${WORK_LABELS[k]||k} ${v}`).join(' · '):'Keine Basisarbeit erfasst'}
function decision(){if(!state.profile.playerLevel)return['Spielerlevel ergänzen','Nur erreichbare Inhalte dürfen berücksichtigt werden.','bestand'];if(!state.profile.goal)return['Ziel festlegen','Ohne konkretes Ziel gibt es keine belastbare Optimierung.','bestand'];if(!state.pals.length)return['Pals aus dem Katalog übernehmen','Wähle deine tatsächlich vorhandenen Pals direkt aus dem Paldex.','paldex'];return[`${state.profile.goal} vorbereiten`,`${state.pals.length} eigene Pals sind eindeutig mit dem Katalog verknüpft.`,'optimieren']}
function dashboard(){const[t,w,target]=decision(),errors=validateCatalog();const confirmed=PAL_CATALOG.filter(p=>p.languageStatus==='de-confirmed').length;return`<section class="hero"><div><p class="eyebrow">NÄCHSTER BESTER SCHRITT</p><h2>${esc(t)}</h2><p>${esc(w)}</p></div><button class="primary" data-go="${target}">Jetzt bearbeiten</button></section><div class="grid"><article class="card"><span class="muted">Katalog</span><div class="metric">${PAL_CATALOG.length}</div><p>strukturierte Pal-Einträge</p></article><article class="card"><span class="muted">Deutsch bestätigt</span><div class="metric">${confirmed}</div><p>offiziell geprüfte Texte</p></article></div><section class="card"><p class="eyebrow">DATENPRÜFUNG</p><h3>${errors.length?'Prüfung benötigt':'Katalog konsistent'}</h3><p>${errors.length?esc(errors.slice(0,3).join(' · ')):'Keine doppelten Schlüssel oder Paldeck-Nummern gefunden.'}</p></section>`}
function bestand(){return`<section class="card"><p class="eyebrow">MEIN SPIELSTAND</p><h3>Berechnungsgrundlage</h3><form id="profileForm" class="form"><div class="field"><label>Spielerlevel</label><input name="playerLevel" type="number" min="1" value="${esc(state.profile.playerLevel)}"></div><div class="field"><label>Welt</label><input name="world" value="${esc(state.profile.world)}"></div><div class="field"><label>Ziel</label><input name="goal" value="${esc(state.profile.goal)}" placeholder="z. B. Lily Hard besiegen"></div><button class="primary">Speichern</button></form></section><section class="card"><div class="section-title"><h2>Meine Pals</h2><button data-go="paldex">Aus Katalog</button></div>${state.pals.length?`<div class="list">${state.pals.map((p,i)=>{const c=PAL_CATALOG.find(x=>x.key===p.catalogId);return`<div class="list-item"><div><strong>${esc(p.name)}</strong><small>${c?deckLabel(c):'Nicht verknüpft'} · ${p.stars||0}★ · Level ${esc(p.level||'offen')}</small></div><button class="secondary compact" data-remove-pal="${i}">×</button></div>`}).join('')}</div>`:`<div class="empty"><strong>Noch keine Pals</strong><p class="muted">Übernimm sie direkt aus dem Paldex.</p></div>`}</section>`}
function filteredCatalog(){const q=search.trim().toLowerCase();return PAL_CATALOG.filter(p=>(!q||`${p.paldeck||''} ${p.name} ${p.element} ${p.partner.name} ${p.partner.description} ${workText(p)}`.toLowerCase().includes(q))&&(!elementFilter||p.element.includes(elementFilter))&&(!workFilter||p.work?.[workFilter])&&(!statusFilter||p.languageStatus===statusFilter))}
function paldex(){if(detailKey)return palDetail();const rows=filteredCatalog();const elements=[...new Set(PAL_CATALOG.flatMap(p=>p.element.split('/')))].sort();return`<section class="hero compact-hero"><div><p class="eyebrow">PALDEX · DATENPAKET 3</p><h2>Strukturierter Offline-Katalog</h2><p>${PAL_CATALOG.length} Einträge mit Elementen, Arbeitseignung, Partnerfähigkeit und Datenstatus.</p></div></section><section class="card filter-grid"><div class="field wide"><label>Suche</label><input id="catalogSearch" value="${esc(search)}" placeholder="Pal, Fähigkeit, Arbeit oder Element"></div><div class="field"><label>Element</label><select id="elementFilter"><option value="">Alle</option>${elements.map(x=>`<option ${elementFilter===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Arbeit</label><select id="workFilter"><option value="">Alle</option>${Object.entries(WORK_LABELS).map(([k,v])=>`<option value="${k}" ${workFilter===k?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Datenstatus</label><select id="statusFilter"><option value="">Alle</option>${Object.entries(DATA_STATUS_LABELS).map(([k,v])=>`<option value="${k}" ${statusFilter===k?'selected':''}>${v}</option>`).join('')}</select></div></section><div class="section-title"><h2>${rows.length} Treffer</h2></div><div class="catalog-list">${rows.map(p=>`<article class="catalog-card"><button class="catalog-open" data-detail="${p.key}"><div class="catalog-head"><div><span class="badge">${deckLabel(p)}</span><h3>${esc(p.name)}</h3></div><span class="verified ${p.languageStatus==='de-pending'?'pending':''}">${esc(DATA_STATUS_LABELS[p.languageStatus])}</span></div><p class="element-line">${esc(p.element)}</p><strong>${esc(p.partner.name)}</strong><p>${esc(p.partner.description)}</p><small>${esc(workText(p))}</small></button><button class="${owned(p.key)?'secondary':'primary'}" data-own="${p.key}" ${owned(p.key)?'disabled':''}>${owned(p.key)?'Im Bestand':'Zu meinem Bestand'}</button></article>`).join('')}</div>${rows.length?'':'<div class="empty">Keine Treffer</div>'}`}
function palDetail(){const p=PAL_CATALOG.find(x=>x.key===detailKey);if(!p){detailKey='';return paldex()}return`<button class="back-link" data-back-detail>‹ Paldex</button><section class="card"><div class="catalog-head"><div><span class="badge">${deckLabel(p)}</span><h2>${esc(p.name)}</h2></div><span class="verified ${p.languageStatus==='de-pending'?'pending':''}">${esc(DATA_STATUS_LABELS[p.languageStatus])}</span></div><p class="element-line">${esc(p.element)}</p><h3>${esc(p.partner.name)}</h3><p>${esc(p.partner.description)}</p></section><section class="card"><h3>Arbeitsfähigkeiten</h3><div class="work-chips">${Object.entries(p.work||{}).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<span class="work-chip">${esc(WORK_LABELS[k]||k)} <b>${v}</b></span>`).join('')||'<p class="muted">Noch nicht erfasst.</p>'}</div></section><section class="card"><h3>Maschinenlesbare Effekte</h3><div class="list">${(p.partner.effects||[]).map(e=>`<div class="list-item"><div><strong>${esc(effectLabel(e.type))}</strong><small>${esc(effectDetail(e))}</small></div></div>`).join('')}</div></section><button class="${owned(p.key)?'secondary':'primary'}" data-own="${p.key}" ${owned(p.key)?'disabled':''}>${owned(p.key)?'Bereits im Bestand':'Zu meinem Bestand'}</button>`}
function effectLabel(type){return({base_work_suitability_boost:'Basis-Arbeitsbonus',pal_element_attack:'Element-Angriff',pal_drop_bonus:'Beutebonus',item_weight_reduction:'Gewichtsreduktion',active_weapon:'Aktive Waffe',active_launcher:'Aktiver Werfer',active_grenade:'Aktive Granate',mount:'Reittier',heal_player:'Automatische Heilung',revive_player:'Wiederbelebung',party_follow_attack:'Begleitangriff',pending_partner_text:'Partnertext ausstehend'})[type]||type.replaceAll('_',' ')}
function effectDetail(e){return Object.entries(e).filter(([k])=>k!=='type').map(([k,v])=>`${k}: ${Array.isArray(v)?v.join(', '):v}`).join(' · ')||'Struktur vorhanden'}
function optimieren(){const ownedCatalog=state.pals.map(p=>PAL_CATALOG.find(x=>x.key===p.catalogId)).filter(Boolean);const baseBoosts=ownedCatalog.filter(p=>p.partner.effects?.some(e=>e.type==='base_work_suitability_boost'));const drops=ownedCatalog.filter(p=>p.partner.effects?.some(e=>e.type==='pal_drop_bonus'));return`<section class="hero"><div><p class="eyebrow">ENTSCHEIDUNGSENGINE</p><h2>Dein Bestand wird ausgewertet</h2><p>PALWERK erkennt bereits strukturierte Basisboni, Beuteboni und Arbeitseignungen.</p></div><button class="primary" data-go="paldex">Bestand erweitern</button></section><div class="grid"><article class="card"><span class="muted">Basisverstärker</span><div class="metric">${baseBoosts.length}</div><p>in deinem Bestand</p></article><article class="card"><span class="muted">Beuteverstärker</span><div class="metric">${drops.length}</div><p>in deinem Bestand</p></article></div><section class="card"><h3>Stärkste Arbeitsrollen</h3>${bestWorkRows(ownedCatalog)}</section>`}
function bestWorkRows(list){const rows=Object.keys(WORK_LABELS).map(k=>({k,best:list.filter(p=>p.work?.[k]).sort((a,b)=>b.work[k]-a.work[k])[0]})).filter(x=>x.best).sort((a,b)=>b.best.work[b.k]-a.best.work[a.k]).slice(0,8);return rows.length?`<div class="list">${rows.map(x=>`<div class="list-item"><div><strong>${esc(WORK_LABELS[x.k])}</strong><small>${esc(x.best.name)}</small></div><span class="badge">Lv. ${x.best.work[x.k]}</span></div>`).join('')}</div>`:'<p class="muted">Noch keine Arbeitspals im Bestand.</p>'}
function mehr(){return`<section class="card"><p class="eyebrow">DATENSTAND</p><h3>${esc(CATALOG_VERSION)}</h3><p>${PAL_CATALOG.length} Pals, davon ${PAL_CATALOG.filter(p=>p.languageStatus==='de-confirmed').length} mit bestätigtem deutschem Text. Unsichere Nummern werden nicht erfunden, sondern als offen markiert.</p></section><section class="card"><h3>Backup</h3><div class="button-stack"><button class="secondary" data-export>Backup exportieren</button><label class="secondary file-button">Backup importieren<input type="file" accept="application/json" data-import></label></div></section>`}
function render(){app.innerHTML=({dashboard,bestand,paldex,optimieren,mehr})[route]();document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.route===route));bind()}
function bind(){document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>navigate(x.dataset.go));document.querySelector('#profileForm')?.addEventListener('submit',async e=>{e.preventDefault();state.profile={...state.profile,...Object.fromEntries(new FormData(e.currentTarget))};await save();render()});document.querySelector('#catalogSearch')?.addEventListener('input',e=>{search=e.target.value;render()});document.querySelector('#elementFilter')?.addEventListener('change',e=>{elementFilter=e.target.value;render()});document.querySelector('#workFilter')?.addEventListener('change',e=>{workFilter=e.target.value;render()});document.querySelector('#statusFilter')?.addEventListener('change',e=>{statusFilter=e.target.value;render()});document.querySelectorAll('[data-detail]').forEach(x=>x.onclick=()=>{detailKey=x.dataset.detail;render();scrollTo({top:0})});document.querySelector('[data-back-detail]')?.addEventListener('click',()=>{detailKey='';render()});document.querySelectorAll('[data-own]').forEach(x=>x.onclick=()=>addOwned(x.dataset.own));document.querySelectorAll('[data-remove-pal]').forEach(x=>x.onclick=async()=>{state.pals.splice(+x.dataset.removePal,1);await save();render()});document.querySelector('[data-export]')?.addEventListener('click',exportBackup);document.querySelector('[data-import]')?.addEventListener('change',importBackup)}
async function addOwned(key){const c=PAL_CATALOG.find(p=>p.key===key);if(!c||owned(key))return;const level=prompt(`Level von ${c.name} (optional)`,'')||'';const stars=Math.max(0,Math.min(4,Number(prompt('Sterne 0–4','0')||0)));state.pals.push({id:crypto.randomUUID(),catalogId:c.key,paldeck:c.paldeck,name:c.name,level,stars,passives:[],skills:[],implants:[]});await save();render()}
function exportBackup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`palwerk-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
async function importBackup(e){try{const f=e.target.files?.[0];if(!f)return;const p=JSON.parse(await f.text());if(!p.profile||!Array.isArray(p.pals))throw new Error();state={...defaultState,...p,schemaVersion:4};await save();render()}catch{alert('Das Backup ist ungültig.')}}
function navigate(next){route=next;if(next!=='paldex')detailKey='';render();scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.tab').forEach(x=>x.onclick=()=>navigate(x.dataset.route));
function connection(){document.querySelector('#offlineStatus').textContent=navigator.onLine?'Lokal bereit':'Offline aktiv'}
addEventListener('online',connection);addEventListener('offline',connection);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');connection();render();
