import { PAL_CATALOG } from './catalog.js';

const p=(key,paldeck,name,element,work)=>({
  key,paldeck,name,element,work,
  partner:{name:'Partnerfähigkeit wird geprüft',description:'Name, Element und Arbeitsfähigkeiten stammen aus dem aktuellen 1.0-Datenstand. Der deutsche Partnerfähigkeitstext wird separat geprüft.',effects:[{type:'pending_partner_text'}]},
  languageStatus:'de-pending',source:'palworld-1.0-core-2026-07',verified:true
});

const PACK=[
p('flambelle','025','Flambelle','Feuer',{kindling:1,handiwork:1,transporting:1,farming:1}),
p('rooby','026','Rooby','Feuer',{kindling:1,farming:1}),
p('mau','027','Mau','Schatten',{gathering:1,farming:1}),
p('mau-cryst','027B','Mau Cryst','Eis',{cooling:1,farming:1}),
p('rushoar','028','Rushoar','Erde',{mining:1}),
p('foxparks','029','Foxparks','Feuer',{kindling:1}),
p('foxparks-cryst','029B','Foxparks Cryst','Eis',{cooling:2}),
p('killamari','030','Killamari','Schatten/Wasser',{watering:1,gathering:1,transporting:2}),
p('killamari-primo','030B','Killamari Primo','Neutral/Wasser',{watering:1,gathering:1,transporting:2}),
p('fuddler','031','Fuddler','Erde',{handiwork:1,mining:1,transporting:1}),
p('eikthyrdeer','032','Eikthyrdeer','Neutral',{lumbering:2}),
p('eikthyrdeer-terra','032B','Eikthyrdeer Terra','Erde',{lumbering:2}),
p('direhowl','033','Direhowl','Neutral',{gathering:1}),
p('caprity','034','Caprity','Gras',{planting:2,farming:1}),
p('caprity-noct','034B','Caprity Noct','Schatten',{planting:2,farming:1}),
p('swee','035','Swee','Eis',{gathering:1,cooling:1}),
p('sweepa','036','Sweepa','Eis',{gathering:2,cooling:3}),
p('turtacle','037','Turtacle','Wasser',{watering:2,mining:1,transporting:1}),
p('turtacle-terra','037B','Turtacle Terra','Wasser/Erde',{watering:2,mining:3,transporting:1}),
p('hangyu','038','Hangyu','Erde',{handiwork:1,gathering:1,transporting:2}),
p('hangyu-cryst','038B','Hangyu Cryst','Eis',{handiwork:3,gathering:2,cooling:2,transporting:3}),
p('woolipop','039','Woolipop','Neutral',{farming:1}),
p('woolipop-terra','039B','Woolipop Terra','Erde',{farming:1}),
p('mozzarina','040','Mozzarina','Neutral',{farming:2}),
p('azurobe','041','Azurobe','Wasser/Drache',{watering:4}),
p('azurobe-cryst','041B','Azurobe Cryst','Eis/Drache',{cooling:4}),
p('sparkit','042','Sparkit','Elektro',{generating:1,handiwork:1,transporting:1,farming:1}),
p('kelpsea','043','Kelpsea','Wasser',{watering:1,farming:1}),
p('kelpsea-ignis','043B','Kelpsea Ignis','Feuer',{kindling:1,farming:1}),
p('ribbuny','044','Ribbuny','Neutral',{handiwork:1,gathering:1,transporting:1}),
p('ribbuny-botan','044B','Ribbuny Botan','Gras',{planting:2,handiwork:2,gathering:2,transporting:1}),
p('jelliette','045','Jelliette','Wasser',{watering:2,handiwork:1,transporting:1}),
p('jellroy','046','Jellroy','Wasser/Schatten',{watering:2,handiwork:1,medicine:1,transporting:1}),
p('amione','047','Amione','Wasser',{watering:1,handiwork:2,transporting:1}),
p('gloopie','048','Gloopie','Wasser/Schatten',{watering:2,handiwork:2,transporting:2}),
p('gloopie-primo','048B','Gloopie Primo','Wasser/Neutral',{watering:2,handiwork:2,transporting:2}),
p('galeclaw','049','Galeclaw','Neutral',{gathering:2}),
p('wispaw','050','Wispaw','Schatten',{handiwork:2,lumbering:1,medicine:1,transporting:1}),
p('nitewing','051','Nitewing','Neutral',{gathering:2}),
p('tombat','052','Tombat','Schatten',{gathering:2,mining:3,transporting:2}),
p('tocotoco','053','Tocotoco','Neutral',{gathering:1}),
p('univolt','054','Univolt','Elektro',{generating:3,lumbering:1}),
p('univolt-cryst','054B','Univolt Cryst','Eis',{lumbering:3,cooling:6}),
p('gobfin','055','Gobfin','Wasser',{watering:2,handiwork:2,transporting:1}),
p('gobfin-ignis','055B','Gobfin Ignis','Feuer',{kindling:2,handiwork:2,transporting:1}),
p('loupmoon','056','Loupmoon','Schatten',{handiwork:2}),
p('loupmoon-cryst','056B','Loupmoon Cryst','Eis',{handiwork:4,cooling:4}),
p('cawgnito','057','Cawgnito','Schatten',{lumbering:2,farming:1}),
p('arsox','058','Arsox','Feuer',{kindling:3,lumbering:2}),
p('muffly','059','Muffly','Eis',{cooling:2,transporting:1}),
p('bristla','060','Bristla','Gras',{planting:2,handiwork:2,gathering:2,medicine:2,transporting:1}),
p('cinnamoth','061','Cinnamoth','Gras',{planting:2,gathering:2,medicine:2}),
p('puffolt','062','Puffolt','Elektro',{generating:2,transporting:1}),
p('elphidran','063','Elphidran','Drache',{lumbering:3}),
p('elphidran-aqua','063B','Elphidran Aqua','Drache/Wasser',{watering:4,lumbering:3}),
p('vanwyrm','064','Vanwyrm','Feuer/Schatten',{kindling:2,transporting:3}),
p('vanwyrm-cryst','064B','Vanwyrm Cryst','Eis/Schatten',{cooling:2,transporting:3}),
p('felbat','065','Felbat','Schatten',{medicine:3}),
p('vaelet','066','Vaelet','Gras',{planting:3,handiwork:3,gathering:3,medicine:3,transporting:2,farming:2}),
p('beegarde','067','Beegarde','Gras',{planting:2,handiwork:2,gathering:3,lumbering:2,medicine:2,transporting:2,farming:3}),
p('elizabee','068','Elizabee','Gras',{planting:4,handiwork:4,gathering:4,lumbering:3,medicine:4}),
p('lovander','069','Lovander','Schatten',{handiwork:3,mining:2,medicine:3,transporting:2}),
p('grintale','070','Grintale','Neutral',{gathering:3}),
p('tarantriss','071','Tarantriss','Schatten',{handiwork:3,gathering:3,medicine:2,transporting:2}),
p('polapup','072','Polapup','Eis/Wasser',{watering:3,cooling:4}),
p('polapup-terra','072B','Polapup Terra','Eis/Erde',{mining:4,cooling:4}),
p('leezpunk','073','Leezpunk','Schatten',{handiwork:2,gathering:1,transporting:1}),
p('leezpunk-ignis','073B','Leezpunk Ignis','Feuer',{kindling:2,handiwork:2,gathering:1,transporting:1}),
p('gorirat','074','Gorirat','Neutral',{handiwork:2,lumbering:3,transporting:3}),
p('gorirat-terra','074B','Gorirat Terra','Erde',{handiwork:2,mining:3,transporting:3}),
p('surfent','075','Surfent','Wasser',{watering:3,farming:2}),
p('surfent-terra','075B','Surfent Terra','Erde',{gathering:3}),
p('robinquill','076','Robinquill','Gras',{planting:2,handiwork:3,gathering:3,lumbering:2,medicine:1,transporting:2}),
p('robinquill-terra','076B','Robinquill Terra','Gras/Erde',{handiwork:3,gathering:3,lumbering:2,medicine:2,transporting:2}),
p('flopie','077','Flopie','Gras',{planting:2,handiwork:2,gathering:2,medicine:1,transporting:1}),
p('wixen','078','Wixen','Feuer',{kindling:3,handiwork:3,transporting:2}),
p('wixen-noct','078B','Wixen Noct','Feuer/Schatten',{kindling:4,handiwork:4,transporting:2}),
p('katress','079','Katress','Schatten',{handiwork:3,medicine:3,transporting:2}),
p('katress-ignis','079B','Katress Ignis','Schatten/Feuer',{kindling:3,handiwork:3,medicine:3,transporting:2}),
p('helzephyr','080','Helzephyr','Schatten',{transporting:4}),
p('helzephyr-lux','080B','Helzephyr Lux','Schatten/Elektro',{generating:4,transporting:5}),
p('elgrove','081','Elgrove','Gras',{planting:3,gathering:2,lumbering:3,mining:2,transporting:3}),
p('elgrove-cryst','081B','Elgrove Cryst','Eis',{lumbering:3,mining:3,cooling:5,transporting:3}),
p('lunaris','082','Lunaris','Neutral',{handiwork:4,gathering:2,transporting:2}),
p('fenglope','083','Fenglope','Neutral',{lumbering:3}),
p('fenglope-lux','083B','Fenglope Lux','Elektro',{generating:5,lumbering:4}),
p('dinossom','084','Dinossom','Gras/Drache',{planting:3,lumbering:3}),
p('dinossom-lux','084B','Dinossom Lux','Elektro/Drache',{generating:3,lumbering:4}),
p('bushi','085','Bushi','Feuer',{kindling:2,handiwork:2,gathering:1,lumbering:3,transporting:2}),
p('bushi-noct','085B','Bushi Noct','Feuer/Schatten',{kindling:2,handiwork:2,gathering:1,lumbering:5,transporting:2}),
p('munchill','086','Munchill','Eis/Wasser',{watering:2,cooling:3,transporting:1}),
p('mammorest','087','Mammorest','Gras/Erde',{planting:4,lumbering:4,mining:4}),
p('mammorest-cryst','087B','Mammorest Cryst','Eis/Erde',{lumbering:5,mining:4,cooling:5}),
p('finsider','088','Finsider','Wasser',{watering:2,transporting:1}),
p('finsider-ignis','088B','Finsider Ignis','Wasser/Feuer',{kindling:2,watering:2,transporting:1}),
p('petallia','089','Petallia','Gras',{planting:4,handiwork:3,gathering:3,medicine:4,transporting:2}),
p('petallia-ignis','089B','Petallia Ignis','Gras/Feuer',{kindling:4,handiwork:3,gathering:3,medicine:4,transporting:2}),
p('leafan','090','Leafan','Gras',{planting:3,handiwork:3,gathering:3,transporting:2}),
p('incineram','091','Incineram','Feuer/Schatten',{kindling:3,handiwork:2,mining:3,transporting:2}),
p('incineram-noct','091B','Incineram Noct','Schatten',{handiwork:3,mining:4,transporting:3}),
p('dazzi','092','Dazzi','Elektro',{generating:3,handiwork:2,transporting:2}),
p('dazzi-noct','092B','Dazzi Noct','Schatten/Elektro',{generating:1,handiwork:1,medicine:1,transporting:2}),
p('pyrin','093','Pyrin','Feuer',{kindling:4,lumbering:2}),
p('pyrin-noct','093B','Pyrin Noct','Feuer/Schatten',{kindling:4,lumbering:3}),
p('relaxaurus','094','Relaxaurus','Drache/Wasser',{watering:3,transporting:3})
];

const existing=new Set(PAL_CATALOG.flatMap(x=>[x.key,String(x.name).toLowerCase()]));
for(const row of PACK){
  if(existing.has(row.key)||existing.has(row.name.toLowerCase())) continue;
  PAL_CATALOG.push(row);
  existing.add(row.key); existing.add(row.name.toLowerCase());
}
PAL_CATALOG.sort((a,b)=>String(a.paldeck||'999Z').localeCompare(String(b.paldeck||'999Z'),undefined,{numeric:true})||a.name.localeCompare(b.name,'de'));
