export const CATALOG_VERSION='1.0-de-seed-2026-08-05';
export const PAL_CATALOG=[
{id:'001',name:'Lamball',partner:{name:'Flauschiger Schild',description:'Kann auf Befehl als Schild ausgerüstet werden. Setze es auf eine Viehfarm und es wird manchmal Wolle abwerfen.'},verified:true},
{id:'002',name:'Cattiva',partner:{name:'Helfende Pfote',description:'Wenn Cattiva im Team ist, trägt es dein Gepäck, was deine Maximallast um 100 erhöht. Der Effekt ist nicht stapelbar.'},verified:true},
{id:'003',name:'Chikipi',partner:{name:'Eier legen',description:'Setze es auf eine Viehfarm und es wird manchmal ein Ei legen.'},verified:true},
{id:'004',name:'Lifmunk',partner:{name:'Lifmunk-Rückstoß',description:'Kann sich auf Befehl auf deinen Kopf setzen und dir mit einer Maschinenpistole Schützenhilfe geben.'},verified:true},
{id:'005',name:'Fuack',partner:{name:'Surftackling',description:'Kann auf Befehl Gegner mit seinem Bodysurfing rammen.'},verified:true},
{id:'005B',name:'Fuack Ignis',partner:{name:'Feuertackling',description:'Kann auf Befehl Gegner mit seinem Feuersurfing rammen.'},verified:true},
{id:'006',name:'Vixy',partner:{name:'Spürfuchs',description:'Setze es auf eine Viehfarm und es wird manchmal Gegenstände ausgraben.'},verified:true},
{id:'007',name:'Celaray',partner:{name:'Reisewind-Gleiter',description:'Wenn dieser Pal im Team ist, verändern sich die Eigenschaften deines Gleiters. Du nimmst keinen Fallschaden und kannst länger und schneller gleiten.'},verified:true},
{id:'007B',name:'Celaray Lux',partner:{name:'Knisterwind-Gleiter',description:'Wenn dieser Pal im Team ist, verändern sich die Eigenschaften deines Gleiters. Du nimmst keinen Fallschaden und kannst länger und schneller gleiten.'},verified:true},
{id:'008',name:'Cremis',partner:{name:'Flauschwolle',description:'Wenn dieser Pal im Team ist, wird der Angriff von Pals des Typs Neutral um 15 % erhöht. Setze Cremis auf eine Viehfarm und es wird manchmal Wolle abwerfen.'},verified:true},
{id:'009',name:'Croajiro',partner:{name:'Trampolinstellung',description:'Kann auf Befehl seinen Bauch aufblasen. Hohe Sprünge sind möglich und bis zur Landung ist dein Angriff um 50 % erhöht.'},verified:true},
{id:'009B',name:'Croajiro Noct',partner:{name:'Schattentrampolin',description:'Ermöglicht hohe Sprünge. Schwachpunkttreffer mit Schatten-Angriffen verursachen 25 % mehr Schaden. Der Effekt ist nicht stapelbar.'},verified:true},
{id:'010',name:'Herbil',partner:{name:'Herbil-Herzmassage',description:'Wenn Herbil im Team ist, kann es dich mit 30 % deiner maximalen LP wiederbeleben.'},verified:true},
{id:'011',name:'Teafant',partner:{name:'Wellnessdusche',description:'Wenn deine LP auf 30 % oder weniger fallen, werden 20 % deiner LP wiederhergestellt. Der Effekt ist nicht stapelbar und hat 120 Sekunden Abklingzeit.'},verified:true},
{id:'012',name:'Gumoss',partner:{name:'Holzfällerassistent',description:'Im Team steigt deine Effizienz beim Holzfällen um 30 % und das Gewicht aller Holzarten sinkt um 40 %. Der Effekt ist nicht stapelbar.'},verified:true},
{id:'013',name:'Pupperai',partner:{name:'Eifriges Helferlein',description:'Im Team verursachen deine Angriffe mit Nahkampfwaffen 10 % mehr Schaden. Der Effekt ist nicht stapelbar.'},verified:true},
{id:'014',name:'Clovee',partner:{name:'Glücksklee',description:'Wenn dieser Pal im Lager ist, steigt bei anderen Arbeitspals das Eignungslevel für Sammeln um 1. Der Effekt ist nicht stapelbar.'},verified:true},
{id:'015',name:'Jolthog',partner:{name:'Britzelbombe',description:'Kann auf Befehl als Handgranate ausgerüstet werden und verursacht beim Aufschlag eine Elektro-Explosion.'},verified:true},
{id:'015B',name:'Jolthog Cryst',partner:{name:'Bibberbombe',description:'Kann auf Befehl als Handgranate ausgerüstet werden und verursacht beim Aufschlag eine Eis-Explosion.'},verified:true},
{id:'016',name:'Depresso',partner:{name:'Koffeinschock',description:'Steigert vorübergehend Bewegungstempo und Arbeitstempo um 100 %. Auf einer Viehfarm kann Depresso Giftdrüsen abwerfen.'},verified:true},
{id:'017',name:'Pengullet',partner:{name:'Pengullet-Kanone',description:'Rüstet dich mit einer Panzerfaust aus, die Pengullet als Munition verschießt. Pengullet wird beim Aufschlag kampfunfähig.'},verified:true},
{id:'017B',name:'Pengullet Lux',partner:{name:'Pengullektro-Kanone',description:'Rüstet dich mit einer Panzerfaust aus, die Pengullet Lux als Munition verschießt. Pengullet Lux wird beim Aufschlag kampfunfähig.'},verified:true},
{id:'018',name:'Penking',partner:{name:'Kühner Meeresbezwinger',description:'Im Team wird die Beute von besiegten Feuer-Pals um 40 % erhöht. Der Effekt ist nicht stapelbar.'},verified:true},
{id:'018B',name:'Penking Lux',partner:{name:'Ampere-Admiral',description:'Schwachpunkttreffer mit Wasser-Angriffen verursachen 25 % mehr Schaden. Der Effekt ist nicht stapelbar.'},verified:true},
{id:'019',name:'Hoocrates',partner:{name:'Weisheit der Schatten',description:'Im Team wird der Angriff von Schatten-Pals um 15 % erhöht. Der Effekt ist nicht stapelbar.'},verified:true},
{id:'020',name:'Melpaca',partner:{name:'Wollpaca',description:'Kann als Reittier genutzt werden. Im Team erhöhen sich Verteidigung und Bewegungstempo von Kingpaca. Auf einer Viehfarm kann es Wolle abwerfen.'},verified:true},
{id:'021',name:'Kingpaca',partner:{name:'König Kraftprotz',description:'Kann als Reittier genutzt werden. Verteidigung und Bewegungstempo erhöhen sich mit jedem Melpaca im Team um 5 %.'},verified:true},
{id:'021B',name:'Kingpaca Cryst',partner:{name:'König Kaltblut',description:'Kann als Reittier genutzt werden. Verteidigung und Bewegungstempo erhöhen sich mit jedem Melpaca im Team um 5 %.'},verified:true},
{id:'022',name:'Daedream',partner:{name:'Dämonischer Traumjäger',description:'Im Team erscheint Daedream in deiner Nähe und greift dein Angriffsziel mit Schatten-Geschossen an. Todesstöße sind dadurch nicht möglich.'},verified:true},
{id:'023',name:'Tanzee',partner:{name:'Zu den (W)affen!',description:'Kann auf Befehl vorübergehend Gegner in der Nähe mit einem Sturmgewehr angreifen.'},verified:true},
{id:'023B',name:'Tanzee Ignis',partner:{name:'Besengter Affe',description:'Kann auf Befehl Gegner in der Nähe eine bestimmte Zeit lang mit einem Feuer-Sturmgewehr angreifen.'},verified:true}
];
