import { PAL_CATALOG } from './catalog.js';

const core=(key,name,element)=>({
  key,paldeck:null,name,element,work:{},
  partner:{name:'Partnerfähigkeit wird geprüft',description:'Dieser Core-Eintrag enthält einen bestätigten Pal-Namen und das Element. Paldeck-Nummer, Arbeitsfähigkeiten und deutscher Partnerfähigkeitstext werden separat verifiziert.',effects:[{type:'pending_partner_text'}]},
  languageStatus:'de-pending',source:'palworld-1.0-core-registry-2026-07',verified:true,coreOnly:true
});

const PACK=[
core('anubis','Anubis','Erde'),
core('astal?','Astegon','Drache/Schatten'),
core('azurmane','Azurmane','Elektro'),
core('bastigor','Bastigor','Eis'),
core('beakon','Beakon','Elektro'),
core('bellanoir','Bellanoir','Schatten'),
core('bellanoir-libero','Bellanoir Libero','Schatten'),
core('blazamut','Blazamut','Feuer'),
core('blazamut-ryu','Blazamut Ryu','Drache/Feuer'),
core('blazehowl','Blazehowl','Feuer'),
core('blazehowl-noct','Blazehowl Noct','Feuer/Schatten'),
core('braloha','Braloha','Gras/Erde'),
core('broncherry','Broncherry','Gras'),
core('broncherry-aqua','Broncherry Aqua','Gras/Wasser'),
core('celesdir','Celesdir','Neutral'),
core('celesdir-noct','Celesdir Noct','Schatten'),
core('chillet','Chillet','Eis/Drache'),
core('chillet-ignis','Chillet Ignis','Feuer/Drache'),
core('cryolinx','Cryolinx','Eis'),
core('cryolinx-terra','Cryolinx Terra','Erde'),
core('dazemu','Dazemu','Erde'),
core('digtoise','Digtoise','Erde'),
core('dogen','Dogen','Neutral'),
core('dualith','Dualith','Erde/Gras'),
core('dualith-noct','Dualith Noct','Erde/Schatten'),
core('dumud','Dumud','Erde/Wasser'),
core('dumud-gild','Dumud Gild','Erde/Wasser'),
core('faleris','Faleris','Feuer'),
core('faleris-aqua','Faleris Aqua','Wasser'),
core('foxcicle','Foxcicle','Eis'),
core('frostallion','Frostallion','Eis'),
core('frostallion-noct','Frostallion Noct','Schatten'),
core('frostplume','Frostplume','Eis'),
core('ghangler','Ghangler','Schatten/Wasser'),
core('ghangler-ignis','Ghangler Ignis','Feuer/Wasser'),
core('gildane','Gildane','Erde'),
core('gildra','Gildra','Schatten/Erde'),
core('grizzbolt','Grizzbolt','Elektro'),
core('hartalis','Hartalis','Neutral'),
core('icelyn','Icelyn','Eis'),
core('jetragon','Jetragon','Drache'),
core('jormuntide','Jormuntide','Drache/Wasser'),
core('jormuntide-ignis','Jormuntide Ignis','Drache/Feuer'),
core('kingpaca','Kingpaca','Neutral'),
core('kingpaca-cryst','Kingpaca Cryst','Eis'),
core('kikit','Kikit','Erde'),
core('kitsun','Kitsun','Feuer'),
core('kitsun-noct','Kitsun Noct','Schatten'),
core('knocklem','Knocklem','Erde'),
core('knocklem-ignis','Knocklem Ignis','Feuer'),
core('lullu','Lullu','Gras'),
core('lyleen','Lyleen','Gras'),
core('lyleen-noct','Lyleen Noct','Schatten'),
core('maraith','Maraith','Schatten'),
core('menasting','Menasting','Schatten/Erde'),
core('menasting-terra','Menasting Terra','Erde'),
core('mimog','Mimog','Neutral'),
core('mossanda','Mossanda','Gras'),
core('mossanda-lux','Mossanda Lux','Elektro'),
core('necromus','Necromus','Schatten'),
core('neptilius','Neptilius','Wasser'),
core('nitemary','Nitemary','Schatten'),
core('nyafia','Nyafia','Schatten'),
core('omascul','Omascul','Schatten'),
core('orserk','Orserk','Drache/Elektro'),
core('paladius','Paladius','Neutral'),
core('palumbra','Palumbra','Gras'),
core('penking-lux','Penking Lux','Wasser/Elektro'),
core('prixter','Prixter','Schatten/Erde'),
core('prixter-lux','Prixter Lux','Elektro/Erde'),
core('prunelia','Prunelia','Gras/Schatten'),
core('quiverN','Quivern','Drache'),
core('quivern-botan','Quivern Botan','Drache/Gras'),
core('ragnahawk','Ragnahawk','Feuer'),
core('rayhound','Rayhound','Elektro'),
core('rayhound-cryst','Rayhound Cryst','Eis'),
core('reindrix','Reindrix','Eis'),
core('reptyro','Reptyro','Feuer/Erde'),
core('reptyro-cryst','Reptyro Cryst','Eis/Erde'),
core('sekHmet','Sekhmet','Erde'),
core('selyne','Selyne','Schatten/Neutral'),
core('shadowbeak','Shadowbeak','Schatten'),
core('shroomer','Shroomer','Gras'),
core('shroomer-noct','Shroomer Noct','Gras/Schatten'),
core('sibelyx','Sibelyx','Eis'),
core('sibelyx-primo','Sibelyx Primo','Neutral'),
core('silvegis','Silvegis','Drache'),
core('smokie','Smokie','Schatten'),
core('smokie-cryst','Smokie Cryst','Schatten/Eis'),
core('snugloo','Snugloo','Eis'),
core('sootseer','Sootseer','Schatten/Feuer'),
core('splatterina','Splatterina','Schatten'),
core('starryon','Starryon','Schatten'),
core('starryon-primo','Starryon Primo','Neutral'),
core('suzaku','Suzaku','Feuer'),
core('suzaku-aqua','Suzaku Aqua','Wasser'),
core('tetroise','Tetroise','Erde'),
core('verdash','Verdash','Gras'),
core('warsect','Warsect','Erde/Gras'),
core('warsect-terra','Warsect Terra','Erde'),
core('whalaska','Whalaska','Eis/Wasser'),
core('whalaska-ignis','Whalaska Ignis','Eis/Feuer'),
core('wumpo','Wumpo','Eis'),
core('wumpo-botan','Wumpo Botan','Gras'),
core('xenogard','Xenogard','Drache'),
core('xenolord','Xenolord','Schatten/Drache'),
core('xenovader','Xenovader','Schatten'),
core('yakumo','Yakumo','Neutral')
];

const existing=new Set(PAL_CATALOG.flatMap(x=>[String(x.key).toLowerCase(),String(x.name).toLowerCase()]));
for(const row of PACK){
  if(existing.has(row.key.toLowerCase())||existing.has(row.name.toLowerCase())) continue;
  PAL_CATALOG.push(row);
  existing.add(row.key.toLowerCase());
  existing.add(row.name.toLowerCase());
}
PAL_CATALOG.sort((a,b)=>String(a.paldeck||'999Z').localeCompare(String(b.paldeck||'999Z'),undefined,{numeric:true})||a.name.localeCompare(b.name,'de'));
