import { loadState, saveState } from './storage.js';
import { PAL_CATALOG, WORK_LABELS } from './catalog.js';
import { PASSIVE_SKILLS } from './generated-core.js';

const app=document.querySelector('#app');
const esc=(v='')=>String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const elements=['Neutral','Feuer','Wasser','Gras','Elektro','Eis','Erde','Schatten','Drache'];
const counters={Feuer:'Wasser',Wasser:'Elektro',Gras:'Feuer',Elektro:'Erde',Eis:'Feuer',Erde:'Gras',Schatten:'Drache',Drache:'Eis',Neutral:'Schatten'};
const effectLabels={pal_element_attack:'Elementschaden',weakpoint_damage:'Schwachpunktschaden',pal_drop_bonus:'Beutebonus',player_attack:'Spielerangriff',player_weapon_damage:'Waffenschaden',player_attack_element_conversion:'Elementumwandlung',party_follow_attack:'Begleitangriff',heal_player:'Heilung',revive_player:'Wiederbelebung',active_weapon:'Aktive Waffe',active_launcher:'Aktiver Werfer',active_grenade:'Aktive Granate',mount:'Mobilität',item_weight_reduction:'Traglast',cooldown_reduction:'Cooldown',base_work_suitability_boost:'Basisverstärker',life_steal:'Lebensraub'};
const effects=p=>p.partner?.effects||[];
const ownedMap=state=>new Map((state.pals||[]).map(p=>[p.catalogId,p]));
const has=(p,types)=>effects(p).some(e=>types.includes(e.type));
const splitElements=p=>String(p?.element||'').split('/').map(x=>x.trim()).filter(Boolean);
const num=v=>Number(v)||0;
const skillPower=s=>num(s?.data?.power??s?.data?.Power??s?.power);
const skillCooldown=s=>num(s?.data?.cooldown??s?.data?.cool_time??s?.data?.CoolTime??s?.cooldown);
const skillElement=s=>String(s?.data?.element??s?.data?.type??s?.type??'');
const offensiveSkills=p=>(p.skills||[]).filter(s=>skillPower(s)>0);
const counterSkills=(p,counter)=>offensiveSkills(p).filter(s=>skillElement(s).toLowerCase().includes(String(counter).toLowerCase()));
const dpsValue=s=>skillPower(s)/Math.max(1,skillCooldown(s)||1);
const detail=p=>Object.keys(p.work||{}).length*2+effects(p).filter(e=>!['pending_partner_text','raw_partner_data'].includes(e.type)).length*5+(p.paldeck?2:0);

const roleDefs={
  damage:{label:'Haupt-DPS',types:['pal_element_attack','weakpoint_damage','active_weapon','active_launcher','active_grenade','party_follow_attack']},
  subdamage:{label:'Schnelle Angriffe',types:['pal_element_attack','party_follow_attack']},
  loot:{label:'Beutebonus',types:['pal_drop_bonus']},
  cooldown:{label:'Cooldown/Tempo',types:['cooldown_reduction','party_follow_attack']},
  sustain:{label:'Überleben',types:['heal_player','revive_player','life_steal']},
  carry:{label:'Traglast',types:['item_weight_reduction']},
  mobility:{label:'Mobilität',types:['mount']},
  player:{label:'Spieler-DPS',types:['player_attack','player_weapon_damage','player_attack_element_conversion','active_weapon','active_launcher']},
  tank:{label:'Tank',types:['heal_player','revive_player','life_steal']},
  utility:{label:'Utility',types:['base_work_suitability_boost']}
};
const clusters=[
  {id:'boss',title:'Boss Optimizer',icon:'⚔',desc:'Tower-, Alpha- und Spezialbosse',needsTarget:true,targetType:'boss',needsDifficulty:true,presets:['Schnellster Kill','Sicherster Kill','Spieler-DPS','Pal-DPS','Hybrid']},
  {id:'raid',title:'Raid Optimizer',icon:'◈',desc:'Bellanoir, Blazamut Ryu, Xenolord und weitere Raids',needsTarget:true,targetType:'raid',needsDifficulty:true,presets:['Solo','Multiplayer','Burst','Sustain','Ultra sicher']},
  {id:'element',title:'Element-Farming',icon:'◎',desc:'Pals eines Elements schnell und mit mehr Beute farmen',needsElement:true,presets:['Maximale Beute','Maximale Geschwindigkeit','Ausgewogen','Sicher']},
  {id:'worldtree',title:'World Tree',icon:'♧',desc:'Holz, Elite, Truhen, Materialien und längere Runs',presets:['Holz-Fokus','Elite-Fokus','Truhen-Fokus','Allround']},
  {id:'materials',title:'Material-Farming',icon:'◆',desc:'Erz, Holz, Stein, Kohle, Schwefel, Öl, Quarz und Chromit',needsMaterial:true,presets:['Base-Produktion','Aktiv farmen','Transport','Maximale Ausbeute']},
  {id:'fishing',title:'Angeln',icon:'≈',desc:'Angel-Runs, Transport, Sicherheit und Rückweg',presets:['Schnellste Route','Maximale Ausbeute','Sicher']},
  {id:'carry',title:'Traglast & Transport',icon:'▣',desc:'Maximales Gewicht, Rückweg und Ressourcentransport',presets:['Maximale Traglast','Schnellster Rückweg','Ausgewogen']},
  {id:'base',title:'Base & Arbeit',icon:'⌂',desc:'Holz, Erz, Transport, Strom, Handwerk, Medizin und Kochen',needsWork:true,presets:['Maximale Produktion','Stabile Basis','Spezialteam']},
  {id:'archetype',title:'Team-Archetypen',icon:'◇',desc:'Hyper Carry, Full Support, Burst, Sustain, Tank und Mobility',needsArchetype:true,presets:['Hyper Carry','Full Support','Spieler-DPS','Pal-DPS','Burst','Sustain','Crowd Control','Tank','Mobility']}
];
const materialOptions=['Holz','Stein','Erz','Kohle','Schwefel','Rohöl','Quarz','Chromit','Hexolith','Pal-Flüssigkeit','Feuerdrüsen','Eisdrüsen','Elektroorgane'];
const workOptions=Object.entries(WORK_LABELS);
const bossCandidates=()=>PAL_CATALOG.filter(p=>p.flags?.boss||p.flags?.towerBoss).sort((a,b)=>a.name.localeCompare(b.name,'de'));
const raidCandidates=()=>PAL_CATALOG.filter(p=>p.flags?.raidBoss||/bellanoir|blazamut ryu|xenolord/i.test(`${p.name} ${p.internalId||''}`)).sort((a,b)=>a.name.localeCompare(b.name,'de'));

function rolesFor(cluster,data){const p=data.preset||data.archetype||'';if(cluster.id==='boss'){if(p==='Sicherster Kill')return['damage','tank','sustain','cooldown','player'];if(p==='Spieler-DPS')return['player','player','damage','cooldown','sustain'];if(p==='Pal-DPS')return['damage','subdamage','damage','cooldown','sustain'];if(p==='Hybrid')return['damage','player','subdamage','sustain','cooldown'];return['damage','subdamage','damage','cooldown','player'];}if(cluster.id==='raid'){if(p==='Sustain'||p==='Ultra sicher')return['damage','tank','sustain','sustain','cooldown'];if(p==='Multiplayer')return['damage','subdamage','player','sustain','cooldown'];if(p==='Burst')return['damage','damage','subdamage','player','cooldown'];return['damage','subdamage','player','sustain','cooldown'];}if(cluster.id==='element')return p==='Maximale Beute'?['damage','loot','loot','cooldown','mobility']:p==='Maximale Geschwindigkeit'?['damage','subdamage','cooldown','mobility','loot']:p==='Sicher'?['damage','loot','sustain','tank','mobility']:['damage','loot','subdamage','cooldown','mobility'];if(cluster.id==='worldtree')return p==='Holz-Fokus'?['utility','carry','mobility','sustain','damage']:['damage','carry','mobility','sustain','subdamage'];if(cluster.id==='materials')return['utility','carry','mobility','damage','cooldown'];if(cluster.id==='fishing')return['mobility','carry','sustain','cooldown','utility'];if(cluster.id==='carry')return['carry','carry','mobility','sustain','damage'];if(cluster.id==='base')return['utility','utility','carry','cooldown','sustain'];return p==='Full Support'?['cooldown','sustain','player','utility','tank']:p==='Tank'?['tank','sustain','damage','cooldown','player']:p==='Mobility'?['mobility','mobility','carry','damage','sustain']:['damage','player','subdamage','cooldown','sustain'];}
function roleScore(p,role,ctx){let score=detail(p);const def=roleDefs[role],pEls=splitElements(p);for(const e of effects(p)){if(def.types.includes(e.type))score+=55;if(ctx.counter&&(e.element===ctx.counter||e.targetElement===ctx.counter))score+=35;if(ctx.targetElement&&e.targetElement===ctx.targetElement)score+=role==='loot'?95:25;}const stats=p.stats||{},difficulty=ctx.difficulty==='Ultra'?1.35:ctx.difficulty==='Schwer'?1.18:1;const matching=counterSkills(p,ctx.counter),pool=matching.length?matching:offensiveSkills(p);const dps=pool.sort((a,b)=>dpsValue(b)-dpsValue(a)).slice(0,3).reduce((sum,s)=>sum+dpsValue(s),0);if(['damage','subdamage'].includes(role)){score+=num(stats.attack)*0.7+dps*18;if(ctx.counter&&pEls.includes(ctx.counter))score+=110;if(role==='subdamage')score+=offensiveSkills(p).filter(s=>skillCooldown(s)>0&&skillCooldown(s)<=8).length*28;}if(role==='tank')score+=(num(stats.hp)*0.7+num(stats.defense)*0.9)*difficulty;if(role==='sustain')score+=(num(stats.hp)+num(stats.defense))*0.35*difficulty;if(role==='player'&&has(p,roleDefs.player.types))score+=120;if(role==='utility'&&ctx.work&&p.work?.[ctx.work])score+=90+p.work[ctx.work]*18;if(role==='carry'&&has(p,['item_weight_reduction']))score+=110;if(role==='loot'&&effects(p).some(e=>e.type==='pal_drop_bonus'&&(!ctx.targetElement||e.targetElement===ctx.targetElement)))score+=150;if(role==='cooldown'&&has(p,['cooldown_reduction']))score+=120;if(role==='mobility'&&has(p,['mount']))score+=100+num(p.movement?.rideSprint)*0.03;return score;}
function pickTeam(source,cluster,ctx,data){const team=[];for(const role of rolesFor(cluster,data)){const ranked=source.filter(p=>p.key!==ctx.target?.key&&!team.some(x=>x.p.key===p.key)).map(p=>({p,score:roleScore(p,role,ctx)})).sort((a,b)=>b.score-a.score||a.p.name.localeCompare(b.p.name,'de'));const best=ranked[0];if(best)team.push({p:best.p,role,score:Math.round(best.score),reason:reason(best.p,role,ctx)});}return team.slice(0,5);}
function reason(p,role,ctx){const relevant=effects(p).filter(e=>roleDefs[role].types.includes(e.type)).map(e=>effectLabels[e.type]).filter(Boolean);if(['damage','subdamage'].includes(role)&&ctx.counter){const skills=counterSkills(p,ctx.counter),fast=skills.filter(s=>skillCooldown(s)>0&&skillCooldown(s)<=8);return`${ctx.counter}-Counter gegen ${ctx.targetElement}; ${skills.length} passende Angriffe${fast.length?`, davon ${fast.length} mit kurzem Cooldown`:''}.`;}if(role==='tank')return`Haltbarkeit aus HP ${num(p.stats?.hp)} und Verteidigung ${num(p.stats?.defense)}.`;if(role==='utility'&&ctx.work&&p.work?.[ctx.work])return`${WORK_LABELS[ctx.work]} Stufe ${p.work[ctx.work]} ist strukturiert erfasst.`;if(relevant.length)return`${roleDefs[role].label}: ${[...new Set(relevant)].join(' · ')}.`;return`${roleDefs[role].label}: beste Kombination aus Kampfwerten, Skills und verfügbaren Effekten.`;}

function recommendedSkills(p,role,ctx){const all=offensiveSkills(p);const matching=counterSkills(p,ctx.counter);const pool=(matching.length?matching:all).map(s=>{let score=dpsValue(s)*10+skillPower(s)*0.15;const cd=skillCooldown(s);if(skillElement(s).toLowerCase().includes(String(ctx.counter).toLowerCase()))score+=80;if(role==='subdamage'||role==='cooldown')score+=cd>0&&cd<=8?65:0;if(role==='damage')score+=skillPower(s)>=100?35:0;if(role==='tank'||role==='sustain')score+=cd>0&&cd<=15?20:0;return{s,score};}).sort((a,b)=>b.score-a.score);const chosen=[];for(const item of pool){if(!chosen.some(x=>x.s.id===item.s.id))chosen.push(item);if(chosen.length===3)break;}return chosen.map(x=>({id:x.s.id,name:x.s.name||x.s.id,level:num(x.s.level),power:skillPower(x.s),cooldown:skillCooldown(x.s),element:skillElement(x.s)||'offen',score:Math.round(x.score)}));}
function passiveText(row){return`${row?.name||row?.localized_name||row?.key||''} ${row?.description||''} ${JSON.stringify(row?.effects||row?.data||'')}`.toLowerCase();}
function passiveProfile(role,ctx){const common=['legend','legendär','serenity','gelassenheit','impatient','ungeduldig'];if(['damage','subdamage'].includes(role))return[...common,'attack','angriff','musclehead','muskelkopf',String(ctx.counter||'').toLowerCase(),'damage','schaden'];if(role==='tank')return[...common,'defense','verteidigung','hp','health','burly','hard skin','robust'];if(role==='sustain')return[...common,'defense','verteidigung','hp','health','recovery','heal','regeneration'];if(role==='player')return['vanguard','vorhut','stronghold','festungsstratege','player attack','spielerangriff','motivational','bewegung'];if(role==='cooldown')return['serenity','gelassenheit','impatient','ungeduldig','cooldown','attack','angriff','legend'];return[...common,'speed','geschwindigkeit','defense','verteidigung'];}
function recommendedPassives(role,ctx){const keywords=passiveProfile(role,ctx);const rows=(PASSIVE_SKILLS||[]).map(row=>{const text=passiveText(row);let score=0;keywords.forEach((k,i)=>{if(k&&text.includes(k))score+=Math.max(5,40-i);});if(/negative|minus|decrease.*attack|angriff.*sinkt|schaden.*sinkt/.test(text))score-=100;return{row,score};}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);const selected=[];for(const x of rows){const name=x.row.name||x.row.localized_name||x.row.key;if(!name||selected.some(y=>y.name===name))continue;selected.push({name,description:x.row.description||'',score:x.score});if(selected.length===4)break;}return selected;}
function soulPlan(role,difficulty){const hard=difficulty==='Ultra'?3:difficulty==='Schwer'?2:1;let attack=0,hp=0,defense=0,work=0;if(['damage','subdamage'].includes(role)){attack=10;hp=hard===3?6:4;defense=hard===3?4:2;}else if(role==='tank'){hp=10;defense=10;attack=hard===1?2:4;}else if(role==='sustain'){hp=10;defense=8;attack=hard===3?4:2;}else if(role==='player'||role==='cooldown'){hp=8;defense=8;attack=4;}else if(role==='utility'){work=10;hp=6;defense=4;}else{hp=6;defense=6;attack=6;}return{attack,hp,defense,work,total:attack+hp+defense+work};}
function targetLevel(skills,ctx,cluster){const unlock=Math.max(1,...skills.map(s=>s.level||1));const base=ctx.difficulty==='Ultra'?70:ctx.difficulty==='Schwer'?60:50;const raidBonus=cluster.id==='raid'?5:0;return Math.min(75,Math.max(unlock,base+raidBonus));}
function buildPlan(member,ctx,cluster){const skills=recommendedSkills(member.p,member.role,ctx);return{skills,passives:recommendedPassives(member.role,ctx),souls:soulPlan(member.role,ctx.difficulty),level:targetLevel(skills,ctx,cluster)};}
function image(p){return p.imageKey?`assets/pals/${p.imageKey}.png`:p.paldeck?`assets/pals/${String(p.paldeck).padStart(3,'0')}.png`:'';}
function buildHtml(x,ctx,cluster){const b=buildPlan(x,ctx,cluster);return`<details class="combat-build"><summary>Kampf-Build anzeigen</summary><div class="build-grid"><div><span class="muted">Ziellevel</span><strong>Level ${b.level}</strong><small>Mindestens bis zum höchsten empfohlenen Skill-Level; ${esc(ctx.difficulty||'Normal')} als Sicherheitsstufe.</small></div><div><span class="muted">Pal-Seelen</span><strong>${b.souls.total} Upgrade-Stufen</strong><small>Angriff ${b.souls.attack}/10 · HP ${b.souls.hp}/10 · Verteidigung ${b.souls.defense}/10${b.souls.work?` · Arbeit ${b.souls.work}/10`:''}</small></div></div><h4>Aktive Skills</h4><div class="build-list">${b.skills.length?b.skills.map(s=>`<div><strong>${esc(s.name)}</strong><small>${esc(s.element)} · Power ${s.power||'offen'} · CD ${s.cooldown||'offen'} s · Freischaltung Lv. ${s.level||'offen'}</small></div>`).join(''):'<p class="muted">Keine ausreichend strukturierten Angriffsskills gefunden.</p>'}</div><h4>Passive Fähigkeiten</h4><div class="build-list">${b.passives.length?b.passives.map(p=>`<div><strong>${esc(p.name)}</strong>${p.description?`<small>${esc(p.description)}</small>`:''}</div>`).join(''):'<p class="muted">Noch keine vier eindeutig passenden Passives im Datenbestand gefunden.</p>'}</div></details>`;}
function teamHtml(team,state,target,ctx,cluster){const own=ownedMap(state);return team.map((x,i)=>{const src=image(x.p),hasPal=own.has(x.p.key);return`<div class="hub-team-row"><span>${i+1}</span>${src?`<img src="${src}" alt="" onerror="this.remove()">`:''}<div><strong>${esc(x.p.name)}</strong><small>${esc(roleDefs[x.role].label)} · ${esc(x.p.element||'Element offen')} · Score ${x.score}${target&&!hasPal?' · fehlt':''}</small><p>${esc(x.reason)}</p>${buildHtml(x,ctx,cluster)}</div></div>`;}).join('');}
function contextFrom(data){const target=PAL_CATALOG.find(p=>p.key===data.target);const targetElement=data.element||splitElements(target)[0]||'';return{target,targetElement,element:targetElement,counter:counters[targetElement]||'',material:data.material||'',work:data.work||'',difficulty:data.difficulty||'Normal',preset:data.preset||'',archetype:data.archetype||''};}

async function openHub(){const state=await loadState({schemaVersion:9,pals:[],teamPlans:[]});app.innerHTML=`<button class="back-link" id="hubBack">‹ Optimieren</button><section class="hero compact-hero"><div><p class="eyebrow">OPTIMIERUNGSZENTRALE</p><h2>Was willst du erreichen?</h2><p>Wähle Ziel, Gegner und Schwerpunkt. PALWERK bewertet Elemente, Kampfwerte, aktive Skills und Partnerfähigkeiten.</p></div></section><div class="hub-clusters">${clusters.map(c=>`<button class="module-card hub-cluster" data-cluster="${c.id}"><div class="module-icon">${c.icon}</div><div><h3>${c.title}</h3><p>${c.desc}</p></div><span class="badge">${c.presets.length}</span></button>`).join('')}</div>`;document.querySelector('#hubBack')?.addEventListener('click',()=>document.querySelector('.tab[data-route="optimieren"]')?.click());document.querySelectorAll('[data-cluster]').forEach(b=>b.addEventListener('click',()=>openCluster(b.dataset.cluster,state)));}
function openCluster(id,state){const c=clusters.find(x=>x.id===id),targets=c.targetType==='raid'?raidCandidates():bossCandidates();app.innerHTML=`<button class="back-link" id="clusterBack">‹ Optimierungszentrale</button><section class="hero compact-hero"><div><p class="eyebrow">${esc(c.title.toUpperCase())}</p><h2>${esc(c.desc)}</h2><p>Jeder Platz erfüllt eine konkrete Rolle. Gegner, Schwierigkeit und Schwerpunkt verändern die Berechnung.</p></div></section><section class="card"><form id="clusterForm" class="form"><div class="field"><label>Planungsbasis</label><select name="scope"><option value="compare">Ziel-Team und Bestand vergleichen</option><option value="all">Alle Pals</option><option value="owned">Nur mein Bestand</option></select></div>${c.needsTarget?`<div class="field wide"><label>${c.targetType==='raid'?'Raid':'Boss'}</label><select name="target" required>${targets.map(x=>`<option value="${x.key}">${esc(x.name)} · ${esc(x.element)}</option>`).join('')}</select></div>`:''}${c.needsDifficulty?`<div class="field"><label>Schwierigkeit</label><select name="difficulty"><option>Normal</option><option>Schwer</option><option>Ultra</option></select></div>`:''}${c.needsElement?`<div class="field"><label>Zu farmendes Element</label><select name="element">${elements.map(x=>`<option>${x}</option>`).join('')}</select></div>`:''}${c.needsMaterial?`<div class="field"><label>Material</label><select name="material">${materialOptions.map(x=>`<option>${x}</option>`).join('')}</select></div>`:''}${c.needsWork?`<div class="field"><label>Arbeitsrolle</label><select name="work">${workOptions.map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></div>`:''}${c.needsArchetype?`<div class="field"><label>Archetyp</label><select name="archetype">${c.presets.map(x=>`<option>${x}</option>`).join('')}</select></div>`:`<div class="field"><label>Schwerpunkt</label><select name="preset">${c.presets.map(x=>`<option>${x}</option>`).join('')}</select></div>`}<button class="primary">Team und Builds simulieren</button></form></section><div id="hubResult"></div>`;document.querySelector('#clusterBack')?.addEventListener('click',openHub);document.querySelector('#clusterForm')?.addEventListener('submit',e=>{e.preventDefault();renderResult(c,Object.fromEntries(new FormData(e.currentTarget)),state);});}
function renderResult(c,data,state){const ctx=contextFrom(data),all=pickTeam(PAL_CATALOG.filter(p=>p?.partner&&p?.name),c,ctx,data),ownSet=ownedMap(state),own=pickTeam(PAL_CATALOG.filter(p=>ownSet.has(p.key)),c,ctx,data),missing=all.filter(x=>!ownSet.has(x.p.key)),sections=[];if(data.scope!=='owned')sections.push(`<section class="card"><p class="eyebrow">OPTIMALES ZIEL-TEAM</p><h3>${esc(ctx.target?.name||c.title)} · ${esc(data.difficulty||data.preset||data.archetype||'Optimiert')}</h3><p class="muted">Gegnerelement ${esc(ctx.targetElement||'offen')} · vorgesehener Counter ${esc(ctx.counter||'offen')}</p><div class="hub-team">${teamHtml(all,state,true,ctx,c)}</div>${missing.length?`<p class="notice"><b>${missing.length} Ziel-Pals fehlen:</b> ${missing.map(x=>esc(x.p.name)).join(' · ')}</p>`:'<p class="notice">Das Ziel-Team ist vollständig vorhanden.</p>'}</section>`);if(data.scope!=='all')sections.push(`<section class="card"><p class="eyebrow">SOFORT SPIELBAR</p><h3>Beste Annäherung aus deinem Bestand</h3><div class="hub-team">${own.length?teamHtml(own,state,false,ctx,c):'<p>Noch keine passenden Bestands-Pals verknüpft.</p>'}</div></section>`);document.querySelector('#hubResult').innerHTML=sections.join('')+`<section class="card"><p class="notice"><b>Simulationsstatus:</b> Skill-Power, Cooldowns, Elemente und Basiswerte stammen aus dem Datenbestand. Ziellevel und Seelenverteilung sind transparente PALWERK-Planwerte, solange exakte Boss-HP-, IV-, Implantat- und Kondensierungsdaten noch nicht vollständig normalisiert sind.</p><button class="secondary" id="saveHubTeam">Teamplan speichern</button></section>`;document.querySelector('#saveHubTeam')?.addEventListener('click',async()=>{const selected=data.scope==='owned'?own:all,name=prompt('Name für den Teamplan',`${c.title} · ${ctx.target?.name||data.element||data.material||data.preset||data.archetype||''}`);if(!name)return;state.schemaVersion=9;state.teamPlans=state.teamPlans||[];state.teamPlans.push({id:crypto.randomUUID(),name,cluster:c.id,clusterLabel:c.title,settings:data,members:selected.map(x=>({catalogId:x.p.key,name:x.p.name,role:x.role,owned:ownSet.has(x.p.key),build:buildPlan(x,ctx,c)})),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});await saveState(state);alert('Teamplan mit Kampf-Builds lokal gespeichert.');});}
function inject(){const grid=app.querySelector('.module-grid');if(!grid||grid.querySelector('[data-optimizer-hub]'))return;const b=document.createElement('button');b.className='module-card';b.dataset.optimizerHub='';b.innerHTML='<div class="module-icon">✦</div><div><h3>Optimierungszentrale</h3><p>Boss, Raid, Builds, Farming und mehr</p></div><span class="badge">Neu</span>';b.addEventListener('click',openHub);grid.prepend(b);}
const style=document.createElement('style');style.textContent='.hub-clusters,.hub-team{display:grid;gap:10px}.hub-team-row{display:grid;grid-template-columns:34px 58px 1fr;gap:10px;align-items:start;padding:13px;border:1px solid var(--line);border-radius:17px;background:rgba(255,255,255,.04)}.hub-team-row>span{width:32px;height:32px;border-radius:11px;display:grid;place-items:center;background:rgba(121,230,197,.12);color:var(--accent);font-weight:800}.hub-team-row img{width:58px;height:58px;object-fit:contain}.hub-team-row strong,.hub-team-row small{display:block}.hub-team-row small{color:var(--muted);margin-top:3px}.hub-team-row p{font-size:12px;margin:6px 0 0!important}.hub-cluster{text-align:left}.combat-build{margin-top:10px;border-top:1px solid var(--line);padding-top:9px}.combat-build summary{cursor:pointer;font-weight:750;color:var(--accent)}.build-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:10px 0}.build-grid>div,.build-list>div{padding:9px;border-radius:12px;background:rgba(255,255,255,.035)}.build-list{display:grid;gap:6px}.combat-build h4{margin:12px 0 6px}@media(max-width:410px){.hub-team-row{grid-template-columns:32px 48px 1fr}.hub-team-row img{width:48px;height:48px}.build-grid{grid-template-columns:1fr}}';document.head.appendChild(style);new MutationObserver(inject).observe(app,{childList:true,subtree:true});inject();