import { loadState, saveState } from './storage.js';
import { PAL_CATALOG } from './catalog.js';
import { DEFAULT_PLAYER, DEFAULT_PAL_PROFILE, encounterOptions, optimizeRaidArmy, simulateBattle, estimatePalDps, recommendPassives, combatStats } from './optimizer-engine-v2.js';

const app=document.querySelector('#app');
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=v=>Number(v)||0;
const byKey=k=>PAL_CATALOG.find(p=>p.key===k);
const img=p=>p?.imageKey?`assets/pals/${p.imageKey}.png`:p?.paldeck?`assets/pals/${String(p.paldeck).padStart(3,'0')}.png`:'';

function defaults(){return{schemaVersion:10,pals:[],teamPlans:[],palProfiles:{},playerLoadout:{...DEFAULT_PLAYER},optimizerV2:{lastType:'raid',lastDifficulty:'Normal'}};}
async function getState(){const s=await loadState(defaults());return{...defaults(),...s,palProfiles:{...(s.palProfiles||{})},playerLoadout:{...DEFAULT_PLAYER,...(s.playerLoadout||{})},optimizerV2:{...defaults().optimizerV2,...(s.optimizerV2||{})}};}

function loadoutForm(player){return`<section class="card"><p class="eyebrow">SPIELER-LOADOUT</p><div class="form"><div class="field"><label>Level</label><input name="playerLevel" type="number" min="1" max="75" value="${n(player.level)}"></div><div class="field"><label>Waffe</label><input name="weaponName" value="${esc(player.weaponName)}"></div><div class="field"><label>Waffen-DPS</label><input name="weaponDps" type="number" min="0" value="${n(player.weaponDps)}"></div><div class="field"><label>Nachladefaktor</label><input name="reloadFactor" type="number" min="0.1" step="0.05" value="${n(player.reloadFactor||1)}"></div><div class="field"><label>Essensmultiplikator</label><input name="foodMultiplier" type="number" min="0.1" step="0.05" value="${n(player.foodMultiplier||1)}"></div><div class="field"><label>Accessoire-Multiplikator</label><input name="accessoryMultiplier" type="number" min="0.1" step="0.05" value="${n(player.accessoryMultiplier||1)}"></div></div></section>`;}

function palProfileForm(pal,profile){const skills=(pal.skills||[]).filter(s=>n(s.level)<=n(profile.level));return`<details class="profile-editor"><summary>${esc(pal.name)} konfigurieren</summary><div class="form"><div class="field"><label>Level</label><input data-pf="level" type="number" min="1" max="75" value="${n(profile.level)}"></div><div class="field"><label>Sterne</label><input data-pf="stars" type="number" min="0" max="4" value="${n(profile.stars)}"></div><div class="field"><label>IV Angriff</label><input data-pf="ivAttack" type="number" min="0" max="100" value="${n(profile.ivs?.attack)}"></div><div class="field"><label>IV HP</label><input data-pf="ivHp" type="number" min="0" max="100" value="${n(profile.ivs?.hp)}"></div><div class="field"><label>IV Verteidigung</label><input data-pf="ivDefense" type="number" min="0" max="100" value="${n(profile.ivs?.defense)}"></div><div class="field"><label>Seelen Angriff</label><input data-pf="soulAttack" type="number" min="0" max="10" value="${n(profile.souls?.attack)}"></div><div class="field"><label>Seelen HP</label><input data-pf="soulHp" type="number" min="0" max="10" value="${n(profile.souls?.hp)}"></div><div class="field"><label>Seelen Verteidigung</label><input data-pf="soulDefense" type="number" min="0" max="10" value="${n(profile.souls?.defense)}"></div><div class="field wide"><label>Passive Fähigkeiten, durch Komma getrennt</label><input data-pf="passives" value="${esc((profile.passives||[]).join(', '))}"></div><div class="field wide"><label>Aktive Skills</label><select data-pf="skills" multiple size="${Math.min(6,Math.max(3,skills.length))}">${skills.map(s=>`<option value="${esc(s.id)}" ${(profile.activeSkillIds||[]).includes(s.id)?'selected':''}>${esc(s.name||s.id)} · Lv. ${n(s.level)}</option>`).join('')}</select></div></div><button class="secondary save-profile" data-pal="${esc(pal.key)}">Profil speichern</button></details>`;}

function armyHtml(result,encounter){return`<section class="card"><p class="eyebrow">RAID-ARMEE</p><h3>${esc(encounter.name)}</h3><div class="metric-grid"><div><span>Gesamt-DPS</span><strong>${Math.round(result.simulation.totalDps).toLocaleString('de-DE')}</strong></div><div><span>Ziel-DPS</span><strong>${Math.round(result.simulation.required?.target||0).toLocaleString('de-DE')}</strong></div><div><span>Prognose</span><strong>${result.simulation.win?'Sieg':'Nicht ausreichend'}</strong></div><div><span>Kampfzeit</span><strong>${Math.round(result.simulation.time)} s</strong></div></div><p class="notice">Modellbandbreite: ${Math.round(result.simulation.range.low).toLocaleString('de-DE')}–${Math.round(result.simulation.range.high).toLocaleString('de-DE')} DPS. Animationen und echte Trefferquote fehlen noch.</p>${result.waves.map((wave,i)=>`<details class="wave"><summary>Welle ${i+1} · ${wave.length} Pals</summary>${wave.map(x=>{const src=img(x.pal),pass=recommendPassives('damage',encounter.elements);return`<div class="army-row">${src?`<img src="${src}" onerror="this.remove()">`:''}<div><strong>${esc(x.pal.name)}</strong><small>${Math.round(x.dps)} Modell-DPS · Zielpassives: ${esc(pass.join(' · '))}</small><p>${x.rotation.map(s=>esc(s.name)).join(' → ')||'Keine Rotation berechenbar'}</p></div></div>`}).join('')}</details>`).join('')}</section>`;}

async function openV2(){const state=await getState();const type=state.optimizerV2.lastType;const diff=state.optimizerV2.lastDifficulty;const opts=encounterOptions(type,diff);app.innerHTML=`<button class="back-link" id="v2Back">‹ Optimieren</button><section class="hero compact-hero"><div><p class="eyebrow">SIMULATOR V2</p><h2>Kampf und Raid-Armee</h2><p>Persönliche Pal-Profile, Spieler-Loadout, Skill-Rotation und DPS-Bandbreite in einer gemeinsamen Pipeline.</p></div></section><form id="v2Form">${loadoutForm(state.playerLoadout)}<section class="card"><div class="form"><div class="field"><label>Typ</label><select name="type"><option value="raid" ${type==='raid'?'selected':''}>Raid</option><option value="tower" ${type==='tower'?'selected':''}>Tower</option></select></div><div class="field"><label>Schwierigkeit</label><select name="difficulty"><option ${diff==='Normal'?'selected':''}>Normal</option><option ${diff==='Schwer'?'selected':''}>Schwer</option></select></div><div class="field wide"><label>Gegner</label><select name="encounter">${opts.map(x=>`<option value="${esc(x.id)}">${esc(x.name)} · Lv. ${x.level} · ${x.hp.toLocaleString('de-DE')} HP</option>`).join('')}</select></div><div class="field"><label>Armeegröße</label><input name="maxSlots" type="number" min="5" max="50" value="20"></div><div class="field"><label>Quelle</label><select name="scope"><option value="all">Alle Pals</option><option value="owned">Nur Bestand</option></select></div></div><button class="primary">Armee simulieren</button></section></form><div id="v2Result"></div><section class="card"><p class="eyebrow">PERSÖNLICHE PAL-PROFILE</p><p>Wähle einen Pal und erfasse Level, Sterne, IVs, Seelen, Passives und aktive Skills.</p><div class="form"><div class="field wide"><label>Pal</label><select id="profilePal">${PAL_CATALOG.map(p=>`<option value="${esc(p.key)}">${esc(p.name)}</option>`).join('')}</select></div></div><div id="profileEditor"></div></section>`;
  document.querySelector('#v2Back')?.addEventListener('click',()=>document.querySelector('.tab[data-route="optimieren"]')?.click());
  const form=document.querySelector('#v2Form');
  form.querySelector('[name="type"]').addEventListener('change',async e=>{state.optimizerV2.lastType=e.target.value;await saveState(state);openV2();});
  form.querySelector('[name="difficulty"]').addEventListener('change',async e=>{state.optimizerV2.lastDifficulty=e.target.value;await saveState(state);openV2();});
  form.addEventListener('submit',async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(form));state.playerLoadout={...state.playerLoadout,level:n(d.playerLevel),weaponName:d.weaponName,weaponDps:n(d.weaponDps),reloadFactor:n(d.reloadFactor),foodMultiplier:n(d.foodMultiplier),accessoryMultiplier:n(d.accessoryMultiplier)};await saveState(state);const encounter=encounterOptions(d.type,d.difficulty).find(x=>x.id===d.encounter);const owned=(state.pals||[]).map(x=>x.catalogId);const result=optimizeRaidArmy({encounter,profiles:state.palProfiles,player:state.playerLoadout,maxSlots:n(d.maxSlots),ownedOnly:d.scope==='owned',ownedIds:owned});document.querySelector('#v2Result').innerHTML=armyHtml(result,encounter);});
  const selector=document.querySelector('#profilePal'),editor=document.querySelector('#profileEditor');
  const renderEditor=()=>{const pal=byKey(selector.value),profile=state.palProfiles[pal.key]||{...DEFAULT_PAL_PROFILE,ivs:{...DEFAULT_PAL_PROFILE.ivs},souls:{...DEFAULT_PAL_PROFILE.souls}};editor.innerHTML=palProfileForm(pal,profile);editor.querySelector('.save-profile')?.addEventListener('click',async()=>{const root=editor.querySelector('.profile-editor'),get=k=>root.querySelector(`[data-pf="${k}"]`);state.palProfiles[pal.key]={level:n(get('level').value),stars:n(get('stars').value),ivs:{attack:n(get('ivAttack').value),hp:n(get('ivHp').value),defense:n(get('ivDefense').value)},souls:{attack:n(get('soulAttack').value),hp:n(get('soulHp').value),defense:n(get('soulDefense').value),work:0},passives:get('passives').value.split(',').map(x=>x.trim()).filter(Boolean),activeSkillIds:[...get('skills').selectedOptions].map(x=>x.value),implants:[]};await saveState(state);alert('Pal-Profil lokal gespeichert.');});};
  selector.addEventListener('change',renderEditor);renderEditor();
}

function inject(){const grid=app.querySelector('.module-grid');if(!grid||grid.querySelector('[data-v2]'))return;const b=document.createElement('button');b.className='module-card';b.dataset.v2='';b.innerHTML='<div class="module-icon">Σ</div><div><h3>Simulator V2</h3><p>Profile, Raid-Armee, Loadout und Zeitmodell</p></div><span class="badge">Beta</span>';b.addEventListener('click',openV2);grid.prepend(b);}
const style=document.createElement('style');style.textContent='.profile-editor,.wave{margin-top:10px;border:1px solid var(--line);border-radius:15px;padding:12px}.profile-editor summary,.wave summary{font-weight:800;cursor:pointer}.army-row{display:grid;grid-template-columns:50px 1fr;gap:10px;padding:10px 0;border-bottom:1px solid var(--line)}.army-row:last-child{border-bottom:0}.army-row img{width:50px;height:50px;object-fit:contain}.army-row small{display:block;color:var(--muted)}.army-row p{margin:4px 0 0;font-size:12px}.metric-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.metric-grid>div{padding:12px;border-radius:14px;background:rgba(255,255,255,.04)}.metric-grid span,.metric-grid strong{display:block}.metric-grid span{color:var(--muted);font-size:12px}';document.head.appendChild(style);new MutationObserver(inject).observe(app,{childList:true,subtree:true});inject();
