import { loadState, saveState } from './storage.js';
import { PAL_CATALOG, WORK_LABELS } from './catalog.js';

const app=document.querySelector('#app');
const esc=(v='')=>String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const elements=['Neutral','Feuer','Wasser','Gras','Elektro','Eis','Erde','Schatten','Drache'];
const counters={Feuer:'Wasser',Wasser:'Elektro',Gras:'Feuer',Elektro:'Erde',Eis:'Feuer',Erde:'Gras',Schatten:'Drache',Drache:'Eis',Neutral:'Schatten'};
const effectLabels={pal_element_attack:'Elementschaden',weakpoint_damage:'Schwachpunktschaden',pal_drop_bonus:'Beutebonus',player_attack:'Spielerangriff',player_weapon_damage:'Waffenschaden',player_attack_element_conversion:'Elementumwandlung',party_follow_attack:'Begleitangriff',heal_player:'Heilung',revive_player:'Wiederbelebung',active_weapon:'Aktive Waffe',active_launcher:'Aktiver Werfer',active_grenade:'Aktive Granate',mount:'Mobilität',item_weight_reduction:'Traglast',cooldown_reduction:'Cooldown',base_work_suitability_boost:'Basisverstärker'};
const effects=p=>p.partner?.effects||[];
const ownedMap=state=>new Map((state.pals||[]).map(p=>[p.catalogId,p]));
const has=(p,types)=>effects(p).some(e=>types.includes(e.type));
const detail=p=>Object.keys(p.work||{}).length*3+effects(p).filter(e=>e.type!=='pending_partner_text').length*6+(p.paldeck?2:0);
const roleDefs={
  damage:{label:'Haupt-DPS',types:['pal_element_attack','weakpoint_damage','active_weapon','active_launcher','active_grenade','party_follow_attack']},
  loot:{label:'Beutebonus',types:['pal_drop_bonus']},
  cooldown:{label:'Cooldown/Tempo',types:['cooldown_reduction','party_follow_attack']},
  sustain:{label:'Überleben',types:['heal_player','revive_player']},
  carry:{label:'Traglast',types:['item_weight_reduction']},
  mobility:{label:'Mobilität',types:['mount']},
  player:{label:'Spieler-DPS',types:['player_attack','player_weapon_damage','player_attack_element_conversion']},
  utility:{label:'Utility',types:['base_work_suitability_boost']}
};
const clusters=[
  {id:'boss',title:'Boss Optimizer',icon:'⚔',desc:'Tower-, Alpha- und Spezialbosse',needsDifficulty:true,presets:['Schnellster Kill','Sicherster Kill','Spieler-DPS','Pal-DPS','Hybrid'],roles:['damage','player','sustain','cooldown','utility']},
  {id:'raid',title:'Raid Optimizer',icon:'◈',desc:'Bellanoir, Blazamut Ryu, Xenolord und weitere Raids',needsDifficulty:true,presets:['Solo','Multiplayer','Burst','Sustain','Ultra sicher'],roles:['damage','damage','player','sustain','cooldown']},
  {id:'element',title:'Element-Farming',icon:'◎',desc:'Pals eines Elements schnell und mit mehr Beute farmen',needsElement:true,presets:['Maximale Beute','Maximale Geschwindigkeit','Ausgewogen','Sicher'],roles:['damage','loot','loot','cooldown','mobility']},
  {id:'worldtree',title:'World Tree',icon:'♧',desc:'Holz, Elite, Truhen, Materialien und längere Runs',presets:['Holz-Fokus','Elite-Fokus','Truhen-Fokus','Allround'],roles:['damage','carry','mobility','sustain','utility']},
  {id:'materials',title:'Material-Farming',icon:'◆',desc:'Erz, Holz, Stein, Kohle, Schwefel, Öl, Quarz und Chromit',needsMaterial:true,presets:['Base-Produktion','Aktiv farmen','Transport','Maximale Ausbeute'],roles:['utility','carry','mobility','damage','cooldown']},
  {id:'fishing',title:'Angeln',icon:'≈',desc:'Angel-Runs, Transport, Sicherheit und Rückweg',presets:['Schnellste Route','Maximale Ausbeute','Sicher'],roles:['mobility','carry','sustain','cooldown','utility']},
  {id:'carry',title:'Traglast & Transport',icon:'▣',desc:'Maximales Gewicht, Rückweg und Ressourcentransport',presets:['Maximale Traglast','Schnellster Rückweg','Ausgewogen'],roles:['carry','carry','mobility','sustain','damage']},
  {id:'base',title:'Base & Arbeit',icon:'⌂',desc:'Holz, Erz, Transport, Strom, Handwerk, Medizin und Kochen',needsWork:true,presets:['Maximale Produktion','Stabile Basis','Spezialteam'],roles:['utility','utility','carry','cooldown','sustain']},
  {id:'archetype',title:'Team-Archetypen',icon:'◇',desc:'Hyper Carry, Full Support, Burst, Sustain, Tank und Mobility',needsArchetype:true,presets:['Hyper Carry','Full Support','Spieler-DPS','Pal-DPS','Burst','Sustain','Crowd Control','Tank','Mobility'],roles:['damage','player','cooldown','sustain','utility']}
];
const materialOptions=['Holz','Stein','Erz','Kohle','Schwefel','Rohöl','Quarz','Chromit','Hexolith','Pal-Flüssigkeit','Feuerdrüsen','Eisdrüsen','Elektroorgane'];
const workOptions=Object.entries(WORK_LABELS);

function roleScore(p,role,ctx){let score=detail(p);const def=roleDefs[role];for(const e of effects(p)){if(def.types.includes(e.type))score+=45;if(ctx.element&&(e.element===ctx.element||e.targetElement===ctx.element))score+=35;if(ctx.targetElement&&e.targetElement===ctx.targetElement)score+=55;}if(role==='damage'&&ctx.counter&&String(p.element).split('/').includes(ctx.counter))score+=65;if(role==='utility'&&ctx.work&&p.work?.[ctx.work])score+=70+p.work[ctx.work]*12;if(role==='carry'&&has(p,['item_weight_reduction']))score+=75;if(role==='loot'&&has(p,['pal_drop_bonus']))score+=90;return score}
function pickTeam(source,cluster,ctx){const team=[];for(const role of cluster.roles){const ranked=source.filter(p=>!team.some(x=>x.p.key===p.key)).sort((a,b)=>roleScore(b,role,ctx)-roleScore(a,role,ctx)||a.name.localeCompare(b.name,'de'));const p=ranked[0];if(p)team.push({p,role,reason:reason(p,role,ctx)});}return team.slice(0,5)}
function reason(p,role,ctx){const relevant=effects(p).filter(e=>roleDefs[role].types.includes(e.type)).map(e=>effectLabels[e.type]).filter(Boolean);if(role==='damage'&&ctx.counter&&String(p.element).includes(ctx.counter))return`${ctx.counter} ist der vorgesehene Element-Counter gegen ${ctx.targetElement}.`;if(role==='utility'&&ctx.work&&p.work?.[ctx.work])return`${WORK_LABELS[ctx.work]} Stufe ${p.work[ctx.work]} ist strukturiert erfasst.`;if(relevant.length)return`${roleDefs[role].label}: ${[...new Set(relevant)].join(' · ')}.`;return`${roleDefs[role].label}: bestbewerteter verfügbarer Kandidat anhand der bestätigten Katalogdaten.`}
function image(p){return p.paldeck?`assets/pals/${String(p.paldeck).padStart(3,'0')}.png`:''}
function teamHtml(team,state,target){const own=ownedMap(state);return team.map((x,i)=>{const src=image(x.p),hasPal=own.has(x.p.key);return`<div class="hub-team-row"><span>${i+1}</span>${src?`<img src="${src}" alt="" onerror="this.remove()">`:''}<div><strong>${esc(x.p.name)}</strong><small>${esc(roleDefs[x.role].label)} · ${esc(x.p.element||'Element offen')} ${target&&!hasPal?'· fehlt':''}</small><p>${esc(x.reason)}</p></div></div>`}).join('')}
function contextFrom(data){const targetElement=data.element||'';return{element:targetElement,targetElement,counter:counters[targetElement]||'',material:data.material||'',work:data.work||'',difficulty:data.difficulty||'',preset:data.preset||'',archetype:data.archetype||''}}

async function openHub(){const state=await loadState({schemaVersion:8,pals:[],teamPlans:[]});app.innerHTML=`<button class="back-link" id="hubBack">‹ Optimieren</button><section class="hero compact-hero"><div><p class="eyebrow">OPTIMIERUNGSZENTRALE</p><h2>Was willst du erreichen?</h2><p>Wähle Ziel, Schwerpunkt und Planungsbasis. PALWERK stellt Rollen statt zufälliger Einzel-Pals zusammen.</p></div></section><div class="hub-clusters">${clusters.map(c=>`<button class="module-card hub-cluster" data-cluster="${c.id}"><div class="module-icon">${c.icon}</div><div><h3>${c.title}</h3><p>${c.desc}</p></div><span class="badge">${c.presets.length}</span></button>`).join('')}</div>`;document.querySelector('#hubBack')?.addEventListener('click',()=>document.querySelector('.tab[data-route="optimieren"]')?.click());document.querySelectorAll('[data-cluster]').forEach(b=>b.addEventListener('click',()=>openCluster(b.dataset.cluster,state)))}
function openCluster(id,state){const c=clusters.find(x=>x.id===id);app.innerHTML=`<button class="back-link" id="clusterBack">‹ Optimierungszentrale</button><section class="hero compact-hero"><div><p class="eyebrow">${esc(c.title.toUpperCase())}</p><h2>${esc(c.desc)}</h2><p>Jeder Platz erfüllt eine konkrete Rolle. Fehlende Pals werden als Ziel-Pals markiert.</p></div></section><section class="card"><form id="clusterForm" class="form"><div class="field"><label>Planungsbasis</label><select name="scope"><option value="compare">Ziel-Team und Bestand vergleichen</option><option value="all">Alle Pals</option><option value="owned">Nur mein Bestand</option></select></div>${c.needsDifficulty?`<div class="field"><label>Schwierigkeit</label><select name="difficulty"><option>Normal</option><option>Schwer</option><option>Ultra</option></select></div>`:''}${c.needsElement?`<div class="field"><label>Zu farmendes Element</label><select name="element">${elements.map(x=>`<option>${x}</option>`).join('')}</select></div>`:''}${c.needsMaterial?`<div class="field"><label>Material</label><select name="material">${materialOptions.map(x=>`<option>${x}</option>`).join('')}</select></div>`:''}${c.needsWork?`<div class="field"><label>Arbeitsrolle</label><select name="work">${workOptions.map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></div>`:''}${c.needsArchetype?`<div class="field"><label>Archetyp</label><select name="archetype">${c.presets.map(x=>`<option>${x}</option>`).join('')}</select></div>`:`<div class="field"><label>Schwerpunkt</label><select name="preset">${c.presets.map(x=>`<option>${x}</option>`).join('')}</select></div>`}<button class="primary">Optimales Team berechnen</button></form></section><div id="hubResult"></div>`;document.querySelector('#clusterBack')?.addEventListener('click',openHub);document.querySelector('#clusterForm')?.addEventListener('submit',e=>{e.preventDefault();renderResult(c,Object.fromEntries(new FormData(e.currentTarget)),state)})}
function renderResult(c,data,state){const ctx=contextFrom(data);const all=pickTeam(PAL_CATALOG.filter(p=>p?.partner&&p?.name),c,ctx);const ownSet=ownedMap(state);const own=pickTeam(PAL_CATALOG.filter(p=>ownSet.has(p.key)),c,ctx);const missing=all.filter(x=>!ownSet.has(x.p.key));const sections=[];if(data.scope!=='owned')sections.push(`<section class="card"><p class="eyebrow">OPTIMALES ZIEL-TEAM</p><h3>${esc(c.title)} · ${esc(data.difficulty||data.preset||data.archetype||'Optimiert')}</h3><div class="hub-team">${teamHtml(all,state,true)}</div>${missing.length?`<p class="notice"><b>${missing.length} Ziel-Pals fehlen:</b> ${missing.map(x=>esc(x.p.name)).join(' · ')}</p>`:'<p class="notice">Das Ziel-Team ist vollständig vorhanden.</p>'}</section>`);if(data.scope!=='all')sections.push(`<section class="card"><p class="eyebrow">SOFORT SPIELBAR</p><h3>Beste Annäherung aus deinem Bestand</h3><div class="hub-team">${own.length?teamHtml(own,state,false):'<p>Noch keine passenden Bestands-Pals verknüpft.</p>'}</div></section>`);document.querySelector('#hubResult').innerHTML=sections.join('')+`<section class="card"><p class="notice">Die Rollenlogik verwendet bestätigte Elemente, Arbeitswerte und strukturierte Partner-Effekte. Fehlende exakte Kampfwerte werden nicht erfunden.</p><button class="secondary" id="saveHubTeam">Teamplan speichern</button></section>`;document.querySelector('#saveHubTeam')?.addEventListener('click',async()=>{const selected=data.scope==='owned'?own:all;const name=prompt('Name für den Teamplan',`${c.title} · ${data.element||data.material||data.preset||data.archetype||''}`);if(!name)return;state.schemaVersion=8;state.teamPlans=state.teamPlans||[];state.teamPlans.push({id:crypto.randomUUID(),name,cluster:c.id,clusterLabel:c.title,settings:data,members:selected.map(x=>({catalogId:x.p.key,name:x.p.name,role:x.role,owned:ownSet.has(x.p.key)})),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});await saveState(state);alert('Teamplan lokal gespeichert.')})}
function inject(){const grid=app.querySelector('.module-grid');if(!grid||grid.querySelector('[data-optimizer-hub]'))return;const b=document.createElement('button');b.className='module-card';b.dataset.optimizerHub='';b.innerHTML='<div class="module-icon">✦</div><div><h3>Optimierungszentrale</h3><p>Boss, Raid, Farming, World Tree, Angeln und mehr</p></div><span class="badge">Neu</span>';b.addEventListener('click',openHub);grid.prepend(b)}
const style=document.createElement('style');style.textContent='.hub-clusters,.hub-team{display:grid;gap:10px}.hub-team-row{display:grid;grid-template-columns:34px 58px 1fr;gap:10px;align-items:center;padding:13px;border:1px solid var(--line);border-radius:17px;background:rgba(255,255,255,.04)}.hub-team-row>span{width:32px;height:32px;border-radius:11px;display:grid;place-items:center;background:rgba(121,230,197,.12);color:var(--accent);font-weight:800}.hub-team-row img{width:58px;height:58px;object-fit:contain}.hub-team-row strong,.hub-team-row small{display:block}.hub-team-row small{color:var(--muted);margin-top:3px}.hub-team-row p{font-size:12px;margin:6px 0 0!important}.hub-cluster{text-align:left}@media(max-width:410px){.hub-team-row{grid-template-columns:32px 48px 1fr}.hub-team-row img{width:48px;height:48px}}';document.head.appendChild(style);new MutationObserver(inject).observe(app,{childList:true,subtree:true});inject();
