import { ACTIVE_SKILL_RECORDS } from '../generated-core.js';
import { PARTNER_DATA } from '../generated-partner-data.js';
import { isOptimizerEligiblePal, readinessForPal } from '../generated-combat-readiness.js';
import { PAL_CATALOG } from '../catalog.js';
import { createCanonicalPalRegistry, isPlayableCatalogPal, resolveCanonicalPal } from '../data/canonical-pals.js';
import { resolvePassive } from '../data/passives.js';

export const KNOWLEDGE_SCHEMA_VERSION='1.6.0';
export const DATA_STATUSES=Object.freeze(['verified','modelled','community-tested','provisional','missing']);
export const ELEMENTS=Object.freeze(['Neutral','Feuer','Wasser','Gras','Elektro','Eis','Erde','Schatten','Drache']);
const ELEMENT_MAP=Object.freeze({Normal:'Neutral',Neutral:'Neutral',Fire:'Feuer',Water:'Wasser',Leaf:'Gras',Grass:'Gras',Electricity:'Elektro',Electric:'Elektro',Ice:'Eis',Ground:'Erde',Earth:'Erde',Dark:'Schatten',Dragon:'Drache'});
export const ELEMENT_COUNTER=Object.freeze({Feuer:'Wasser',Wasser:'Elektro',Gras:'Feuer',Elektro:'Erde',Eis:'Feuer',Erde:'Gras',Schatten:'Drache',Drache:'Eis',Neutral:'Schatten'});
const text=value=>String(value??'').trim();
const number=value=>value==null||value===''?null:Number.isFinite(Number(value))?Number(value):null;
const list=value=>Array.isArray(value)?value:[];
const slug=value=>text(value).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const dexToken=value=>{const raw=text(value).toUpperCase().replace(/[^0-9A-Z]/g,'');const match=raw.match(/^0*(\d+)([A-Z]*)$/);return match?`${Number(match[1])}${match[2]}`:raw;};
const registryDexToken=row=>`${Number(row?.dexNumber)||0}${row?.variantId&&row.variantId!=='base'?String(row.variantId).toUpperCase():''}`;
const partnerByDex=new Map(list(PARTNER_DATA).map(row=>[dexToken(row.paldeck),row]));
const partnerByName=new Map(list(PARTNER_DATA).filter(row=>row?.palName).map(row=>[slug(row.palName),row]));
export function normalizeInternalId(value){return slug(text(value).replace(/^EPalWazaID::/,'').replace(/^EPalPassiveSkillID::/,''));}
export function normalizeElement(value){const raw=text(value);return ELEMENT_MAP[raw]||raw||'Neutral';}
export function field(value,{source='PALWERK',gameVersion=null,verifiedAt=null,confidence='low',status='missing'}={}){return Object.freeze({value:value??null,source,gameVersion,verifiedAt,confidence,status:DATA_STATUSES.includes(status)?status:'missing'});}
export const isPlayablePal=pal=>isPlayableCatalogPal(pal)&&isOptimizerEligiblePal(pal);
function skillRecord(skill){return skill?.data||ACTIVE_SKILL_RECORDS?.[skill?.id]||ACTIVE_SKILL_RECORDS?.[`EPalWazaID::${skill?.id}`]||null;}
function skillNode(skill){const record=skillRecord(skill)||{},id=normalizeInternalId(skill?.id||record?.id||skill?.name),rawPower=number(record.power??skill?.power),cooldown=number(record.cool_time??record.cooldown??skill?.cooldown),animation=number(record.animation),hitRate=number(record.hit_rate);return Object.freeze({id,catalogId:text(skill?.id||record?.id),name:text(skill?.name||record?.name||skill?.id)||'Unbekannter Skill',element:normalizeElement(record.element??skill?.element),unlockLevel:number(skill?.level),rawPower:field(rawPower,{source:'generated-core',confidence:rawPower==null?'low':'high',status:rawPower==null?'missing':'verified'}),cooldown:field(cooldown,{source:'generated-core',confidence:cooldown==null?'low':'high',status:cooldown==null?'missing':'verified'}),animation:field(animation,{source:'generated-core',confidence:animation==null?'low':'medium',status:animation==null?'missing':'provisional'}),hitRate:field(hitRate,{source:'generated-core',confidence:hitRate==null?'low':'medium',status:hitRate==null?'missing':'provisional'}),multiHit:field(number(record.multi_hit),{source:'generated-core',status:record.multi_hit==null?'missing':'provisional'}),aoe:field(number(record.aoe),{source:'generated-core',status:record.aoe==null?'missing':'provisional'}),range:field(record.range??null,{source:'generated-core',status:record.range==null?'missing':'provisional'})});}
function effectNode(effect,index,palId){return Object.freeze({id:normalizeInternalId(effect?.id||`${palId}-${effect?.type||'effect'}-${index}`),type:text(effect?.type)||'unknown',activation:text(effect?.activation)||'unknown',requiresEquipment:Boolean(effect?.requiresEquipment),equipmentId:effect?.equipmentId||null,stackingGroup:text(effect?.stackingGroup)||null,stackable:effect?.stackable===true?true:effect?.stackable===false?false:null,target:effect?.target||null,element:effect?.element?normalizeElement(effect.element):null,valuesByRank:Array.isArray(effect?.valuesByRank)?effect.valuesByRank.slice(0,5):null,appliesTo:list(effect?.appliesTo),conditions:list(effect?.conditions),source:effect?.source||null,gameVersion:effect?.gameVersion||null,verifiedAt:effect?.verifiedAt||null,confidence:effect?.confidence||'low',status:DATA_STATUSES.includes(effect?.status)?effect.status:'missing'});}
function mergedPartnerEffects(registryRow){const pal=registryRow.source;const generated=partnerByName.get(slug(registryRow.displayName))||partnerByDex.get(registryDexToken(registryRow));const legacy=list(pal?.partner?.effects);const combined=[...legacy,...list(generated?.effects)];const map=new Map();for(const effect of combined){const key=JSON.stringify([effect?.type,effect?.activation,effect?.element||effect?.targetElement||null,effect?.target||null,effect?.stackingGroup||null]);map.set(key,effect);}return{effects:[...map.values()],name:text(generated?.skillName||pal?.partner?.name)};}
function roleHints(pal,skills,effects){const roles=new Set();if(skills.some(skill=>(skill.rawPower.value||0)>0))roles.add('active_damage');for(const effect of effects){if(['pal_element_attack','weakpoint_damage','pal_attack','party_pal_attack'].includes(effect.type))roles.add('pal_damage_support');if(['cooldown_reduction','party_follow_attack'].includes(effect.type))roles.add('tempo_support');if(['player_attack','player_weapon_damage'].includes(effect.type))roles.add('player_support');if(['heal_player','revive_player','life_steal','damage_reduction'].includes(effect.type))roles.add('sustain_support');if(['pal_drop_bonus','loot_bonus','farm_drop','manual_duplicate'].includes(effect.type))roles.add('loot_support');}if(Object.values(pal?.work||{}).some(value=>Number(value)>0))roles.add('base_worker');return[...roles];}
function palNode(registryRow){const pal=registryRow.source,id=registryRow.canonicalId,skills=list(pal.skills).map(skillNode).filter(skill=>skill.id),partner=mergedPartnerEffects(registryRow),effects=partner.effects.map((effect,index)=>effectNode(effect,index,id)),fixedPassives=list(pal.fixedPassives||pal.passives).map(passive=>resolvePassive(typeof passive==='string'?passive:passive?.id)).filter(Boolean),readiness=readinessForPal(pal);return Object.freeze({id,canonicalId:id,dexNumber:registryRow.dexNumber,dexKey:registryRow.dexKey,variantId:registryRow.variantId,displayNumber:registryRow.displayNumber,catalogId:text(pal.key||pal.internalId),sourceIds:registryRow.sourceIds,internalId:text(pal.internalId||pal.key),name:registryRow.displayName,playable:isPlayablePal(pal),dataReadiness:readiness,elements:text(pal.element).split('/').map(normalizeElement).filter(Boolean),stats:Object.freeze({hp:number(pal.stats?.hp),attack:number(pal.stats?.attack),defense:number(pal.stats?.defense)}),skills,fixedPassives:Object.freeze(fixedPassives),partner:Object.freeze({name:partner.name,effects}),roles:roleHints(pal,skills,effects),work:Object.freeze({...pal.work}),sourceRef:pal});}
function relationNodes(pals){const relations=[];for(const pal of pals)for(const effect of pal.partner.effects){if(effect.element)relations.push(Object.freeze({from:pal.id,to:`element:${effect.element}`,type:'supports_element',effectId:effect.id,activation:effect.activation,status:effect.status}));if(effect.target)relations.push(Object.freeze({from:pal.id,to:`target:${normalizeInternalId(effect.target)}`,type:'supports_target',effectId:effect.id,activation:effect.activation,status:effect.status}));if(['player_attack','player_weapon_damage'].includes(effect.type))relations.push(Object.freeze({from:pal.id,to:'player',type:'supports_player',effectId:effect.id,activation:effect.activation,status:effect.status}));if(['heal_player','revive_player','life_steal','damage_reduction'].includes(effect.type))relations.push(Object.freeze({from:pal.id,to:'team',type:'supports_survival',effectId:effect.id,activation:effect.activation,status:effect.status}));}return Object.freeze(relations);}
export function createCombatKnowledgeGraph(input=PAL_CATALOG){const registry=Array.isArray(input)?createCanonicalPalRegistry(input):input,pals=Object.freeze(registry.rows.map(palNode)),byId=new Map(),byCatalogId=new Map(),byDexKey=new Map();for(const pal of pals){if(!byId.has(pal.id)||pal.variantId==='base')byId.set(pal.id,pal);byDexKey.set(pal.dexKey,pal);for(const sourceId of pal.sourceIds)byCatalogId.set(sourceId,pal);byCatalogId.set(pal.catalogId,pal);byCatalogId.set(pal.internalId,pal);}return Object.freeze({schemaVersion:KNOWLEDGE_SCHEMA_VERSION,pals,relations:relationNodes(pals),byId,byCatalogId,byDexKey,registry,createdFrom:'PAL_CATALOG_PLUS_PARTNER_DATA_PLUS_COMBAT_READINESS'});}
export const COMBAT_GRAPH=createCombatKnowledgeGraph(PAL_CATALOG);
export function getPalKnowledge(id,options={}){const direct=COMBAT_GRAPH.byId.get(normalizeInternalId(id))||COMBAT_GRAPH.byCatalogId.get(id)||COMBAT_GRAPH.byDexKey.get(id);if(direct)return direct;const registryRow=resolveCanonicalPal(id,options);if(registryRow)return COMBAT_GRAPH.byDexKey.get(registryRow.dexKey)||null;return null;}
export function encounterPhases(encounter={}){const phases=list(encounter.phases);if(!phases.length)return Object.freeze([{id:'phase-1',hpShare:1,elements:list(encounter.elements).map(normalizeElement),resistances:{},recommendedCounters:list(encounter.elements).map(normalizeElement).map(element=>ELEMENT_COUNTER[element]).filter(Boolean),status:'modelled'}]);const fallback=1/phases.length;return Object.freeze(phases.map((phase,index)=>Object.freeze({id:phase.id||`phase-${index+1}`,hpShare:number(phase.hpShare)??fallback,elements:list(phase.elements||encounter.elements).map(normalizeElement),adds:list(phase.adds),clone:Boolean(phase.clone),healing:phase.healing??null,transition:phase.transition??null,resistances:phase.resistances||{},recommendedCounters:list(phase.recommendedCounters).map(normalizeElement),status:phase.status||'provisional'})));}
export function graphQualitySummary(graph=COMBAT_GRAPH){const skills=graph.pals.flatMap(pal=>pal.skills),effects=graph.pals.flatMap(pal=>pal.partner.effects),fixedPassives=graph.pals.flatMap(pal=>pal.fixedPassives);return Object.freeze({playablePals:graph.pals.filter(pal=>pal.playable).length,totalPals:graph.pals.length,uniqueCanonicalIds:graph.registry.byCanonicalId.size,uniqueDexKeys:graph.registry.byDexKey.size,duplicateDexKeys:graph.registry.duplicateDexKeys.length,exactDuplicates:graph.registry.exactDuplicates.length,skills:skills.length,skillsWithPower:skills.filter(skill=>skill.rawPower.status==='verified').length,skillsWithAnimation:skills.filter(skill=>skill.animation.value!=null).length,partnerEffects:effects.length,verifiedPartnerEffects:effects.filter(effect=>effect.status==='verified').length,effectsWithRankValues:effects.filter(effect=>Array.isArray(effect.valuesByRank)).length,inPartyCombatEffects:effects.filter(effect=>effect.activation==='in_party'&&['pal_element_attack','weakpoint_damage','pal_attack','party_pal_attack','cooldown_reduction','party_follow_attack','damage_reduction','heal_player','revive_player','life_steal','player_attack','player_weapon_damage'].includes(effect.type)).length,fixedPassives:fixedPassives.length,structuredFixedPassives:fixedPassives.filter(passive=>passive.effects.some(effect=>effect.stat)).length,optimizerEligiblePals:graph.pals.filter(pal=>pal.dataReadiness?.optimizerEligible).length,excludedByDataGate:graph.pals.filter(pal=>!pal.dataReadiness?.optimizerEligible).length});}
